## Fake News Classifier Using LSTM

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv(r"D:\CODING\PYTHON\NLP\9.LSTM\fake_or_real_news.csv")

In [7]:
df.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [8]:
df.shape

(6335, 4)

In [10]:
df.drop(columns=["Unnamed: 0"],inplace=True)

In [12]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [13]:
###Drop Nan Values
df=df.dropna()

In [14]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [15]:
from sklearn.preprocessing import LabelEncoder

la=LabelEncoder()
df["label"]=la.fit_transform(df["label"])

In [16]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [17]:
## Get the Dependent features
y=df['label']

In [18]:
X.shape

(6335, 2)

In [19]:
y.shape

(6335,)

In [20]:
import tensorflow as tf

In [21]:
tf.__version__

'2.20.0'

In [22]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [23]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [24]:
messages=X.copy()

In [25]:
messages['title'][1]

'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)'

In [26]:
messages

,title,text
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello..."
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T..."
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...
...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene..."
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...

In [27]:
#messages.reset_index(inplace=True)

In [28]:
messages

,title,text
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello..."
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T..."
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...
...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene..."
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...

In [29]:
import nltk
import re
from nltk.corpus import stopwords

In [30]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sinha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [31]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [32]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special guest randi j',
 'hillari clinton make bipartisan appeal staten island',
 'new senat major leader main goal gop scari',
 'inferno overpopul myth',
 'anti trump forc seek last ditch deleg revolt',
 'sander trounc clinton w va make differ',
 'donald trump chang campaign slogan prove racist',
 'pure chao donald trump campaign manag offer glimps govern style spoiler alert terribl',
 'syrian war report novemb syrian militari deploy advanc battl tank aleppo',
 'gop insid carli crush',
 'jeffrey sewel et al metabiolog face face artifici intellig video',
 'necessari relax stretch',
 'brexit encourag uk trade non eu state includ russia',
 'interview socrat anoth day life empir near endgam fool ever hope chang',
 'mike penc drape shawl immodest ladi justic statu onion america finest news sourc',
 'first ever hindu woman elect congress',
 'donald grope hillari trump weiner sext',
 'ex assist fbi director clinton crime famili',
 'hillari want aggress interventionist foreign polici',
 'parti want craft populist messag',
 'first take wall street bid goodby june hike',
 'real disclosur secret alien base found moon tycho crater',
 'homeless woman protect trump walk fame star violent leftist',
 'tweet storm saturday clinton continu mock trump friday meltdown',
 'signific pipelin spill alreadi year expos troubl safeti record',
 'obama make right call tough afghanistan',
 'senat race rank dem attack gop lay swing state groundwork',
 'know boy want rape court throw muslim migrant child sex charg german shock',
 'pieczenik rogu fbi agent wikileak spearhead movement stop clinton steal white hous truthfe',
 'american polit reach peak polar',
 'anti muhammad cartoon contest free speech deliber provoc video',
 'effect substanc abus individu famili commun',
 'tree shape vertic farm grow acr urban crop',
 'new comment featur ad',
 'world newspap react hebdo attack',
 'ying yang gold silver set',
 'close primari warp democraci',
 'polic turn badg rather incit violenc stand rock protestor',
 'donald trump hillari clinton caus tremend death',
 'detroit women halloween decor depict real life horror shoot polic polic',
 'biden make anoth surpris polit stop',
 'hillari clinton declin favor number context',
 'comment quid pro quo wikileak email reveal clinton campaign eye paul ryan rel suprem court lenor lee',
 'hillari clinton crimin investig keep move forward',
 'rubio part shot trump',
 'loretta lynch becom first african american woman ag',
 'funni republican upset facebook column',
 'fbi check orlando shooter wife knew attack plan warn polic',
 'googl youtub hillari purs',
 'handicap hispan vote goper',
 'truth radio laconia incid',
 'gop establish nightmar ted cruz vs donald trump',
 'berni sander lost poor voter south carolina big margin problem polit revolut',
 'get botox',
 'jeb bush pick endors lindsey graham',
 'republican race enter new volatil phase',
 'hand shoot built lie',
 'lavrov kerri discuss syrian settlement',
 'break doj say help review k email truthfe',
 'berni sander call ouster two convent co chair reject',
 'five reason new york democrat primari felt competit',
 'get around congress obama turn citi hall',
 'celebr deathmatch darkmoon sage make final predict us elect',
 'john kerri isi respons genocid',
 'mitt romney invent anti poverti warrior',
 'king fill suprem court vacanc',
 'ted cruz toast presid day senat number',
 'obama speech selma answer question love america',
 'berni sander go',
 'exclus gop campaign plot revolt rnc',
 'revel unleash unlock mysteri bibl mysteri book',
 'silent counter coup intel agenc stop crook clinton video',
 'hillari clinton berni sander town hall',
 'french polic hunt two brother accus charli hebdo terror attack',
 'mandela effect made one overlook year old man ascend master video proof',
 'cnn one voter make differ vote repeatedli',
 'give social secur recipi ceo style rais',
 'firework erupt trump bush rubio cruz gop debat',
 'obama sound like critic admit complet strategi iraq',
 'ted cruz becam ted cruz',
 'newli approv gm potato potenti silenc human gene',
 'accord reach sander sue dnc suspend access critic voter list',
 'latest patriot act reform enough rein nsa',
 'fbi expand probe clinton email launch independ classif review',
 'gari johnson',
 'arcturian group marilyn raffael octob video',
 'nuclear weapon question',
 'kevin macdonald celebr trump amaz victori',
 'amaz aqutru water filter version stock snag unit natur news reader deep discount',
 'happen clinton drop',
 'brother id suicid bomber belgium',
 'glorifi violenc',
 'russia may run patienc respond usa rude',
 'david duke show hillari treason trump duke win',
 'blame immigr san francisco shoot',
 'netanyahu allow israel submerg refuge',
 'apocalyps trump voter warn revolut clinton win',
 'geo engin unlik work conserv group say',
 'question ahead tonight democrat debat',
 'obama terror strategi fail us must heed lesson',
 'berni need ground pulp leak email john podesta februari',
 'selma year john lewi recal march',
 'long overdu presidenti assassin anyway',
 'flip flop vox warn seriou risk elect day violenc good kind either',
 'third parti presidenti candid fight poll spot debat',
 'bush rubio kasich eye one anoth shadow trump',
 'comey must explain advis obama publicli accus russia hack democrat',
 'putin congratul trump say russia readi restor relat us',
 'monsieur malbrough est mort new eastern outlook',
 'conspiraci theori swirl around death antonin scalia',
 'one elect thread ehhh',
 'mccain trump understand syria',
 'trump manag say undercov voter deliv win us elect',
 'wikileak bill clinton differ bill cosbi podestaemail',
 'report megyn trash trump newt murdoch announc replac avail',
 'suspect captur ambush style kill two iowa cop',
 'thing everi american know donald trump plan save u economi',
 'next presid big impact climat polici even without congress',
 'look shock number kid born illeg',
 'mother daughter remind msnbc report trump black support',
 'justic depart staffer monitor poll elect day',
 'elizabeth warren blast fbi director go hillari instead wall street crook',
 'poll percent dem think clinton keep run even indict',
 'trump',
 'iran deal unravel think institut',
 'saturn baffl hexagon rage storm four time size earth chang color',
 'cyru mistri renam rohit sharma mistri get job back',
 'fbi interven elect',
 'donald trump win year month day old first full day offic',
 'shutdown clash return forc decemb',
 'classless obama refus photo op white hous welcom trump',
 'comment maryland trump support switch vote hillari misterdawg',
 'stuff news one talk elect',
 'blizzard charg countercharg melt away opinion trump clinton frozen',
 'social media censor fbi open clinton email investig',
 'obama inch closer veto proof support iran nuclear deal',
 'clinton plan stop sander momentum',
 'martin malley prais senat democrat hold trade deal',
 'shi ite militia join iraq mosul attack',
 'super pac get earli start push clinton campaign',
 'christian attack us must promot religi freedom',
 'u taxpay pay million dollar year privileg spi',
 'video journalist shot militar polic stand rock conduct interview',
 'buffett ran fed would rais rate significantli',
 'tension russia even real',
 'iran agre nuclear restrict framework deal world power',
 'comment constip bodi constip bodi thehealtholog',
 'fifteen quot prove fals flag terror exist shadow govern',
 'berni sander vast univers donor map',
 'former ambassador andrew young call end water fluorid civil right issu',
 'trump new ad portray everi mother worst nightmar noth short chill',
 'undercov video expos obama plan make american gun law like britain truthfe',
 'happen obama forget gop run congress',
 'syrian war report novemb isi al nusra attempt cut govt suppli line aleppo',
 'christian celebr halloween',
 'sunday charleston worship emanuel ame',
 'make matter wors syria',
 'fact check hillari clinton speech democrat convent annot',
 'bust clinton foundat directli tie plot steal elect',
 'connecticut becom first state boycott indiana lgbt discrimin law',
 'scott walker confront doubt grasp foreign polici',
 'iran carri new ballist missil test',
 'assang donald trump allow win clinton isi fund interest',
 'joe biden get respect',
 'come paul ryan must run right right',
 'berni sander need start win big state big',
 'leak obama trade deal',
 'michael moor admit women ever melt ice cap bomb american histori',
 'someon tell truth freddi gray death',
 'prison employe plead guilti aid escap two murder',
 'culchi tri explain rule one time',
 'elect day legal pot ohio democrat lose south',
 'presid trump coloss failur democraci terrifi new realiti',
 'go',
 'raqqa mosul politician fiddl middl east burn',
 'chri christi lose home state donor jeb bush make inroad',
 'washington home depot store receiv order five thousand gallon gold exterior paint',
 'western lynch mob russia tie absurd anot inform',
 'sander ralli support around clinton dnc email leak',
 'histor climat deal sight nation pars final text',
 'live time individu immens power',
 'trump slam corrupt media women make sexual assault claim',
 'dement imbecil want killari reign terror',
 'anti trump advert side bu realli visual clever see motion',
 'american disconnect realiti insouci becom euphem',
 'unspoken rule cover hillari clinton',
 'hillari melt weiner public pic prove campaign implod',
 'clinton vs trump latest elector predict greg laden blog scienc technolog',
 'jubile year merci end novemb follow judgment',
 'iraq launch oper isi anbar provinc',
 'ukip mep steven woolf mike hookem report french polic strasbourg scuffl',
 'justic kennedi scalia divid gay right',
 'justic clarenc thoma describ washington dc broken',
 'week pictur week octob onion america finest news sourc',
 'jeb bush foreign polici plan militari spend encourag peac',
 'john kasich conserv least sane',
 'audio emerg hillari clinton propos rig palestin elect',
 'author search clue raid thwart potenti belgian charli hebdo attack',
 'classic footbal banner time',
 'tweetwav',
 'trump gettysburg address new world order',
 'debat goal democrat candid',
 'spin speak email show pentagon readi roll benghazi attack occur',
 'case studi obamacar lawsuit base mythic histori',
 'trump proudli declar peopl insult deserv',
 'dem sue gop trump rig complaint',
 'us airstrik iraqi armi slow advanc mosul',
 'iran letter blowback startl gop',
 'clinton camp desper russia train wwiii',
 'donald trump gop civil war',
 'comment taint measl vaccin kill children syria tragic death use promot vaccin fear fenc vaccin',
 'laura bush hint rather see hillari presid',
 'scott walker rick perri show limit super pac',
 'catcal polit correct',
 'hillari unleash wwiii inform',
 'time reconsid lifetim appoint suprem court',
 'clinton deleg win dem nomin ap report sander question talli',
 'hillari implod trump took everyth paid noth support us',
 'trump say obama born us period new birther dust',
 'mh debri part miss plane next',
 'googl plan massiv ai integr social network spi tool hillari campaign',
 'israel stole classifi us inform use help congression republican',
 'america simpl ideolog one russia top us expert explain america',
 'poll show trump made point week like poll',
 'chao hous floor dem republican clash lgbt propos',
 'new studi link fluorid consumpt hypothyroid weight gain wors',
 'clinton sander accus trump incit violenc',
 'memo next administr defens spend must actual defens',
 'new respons hillari clinton insist email setup matter conveni',
 'trump mull altern option make mexico financ wall',
 'circu liar america three ring evil clown',
 'donald trump said univers educ actual goal sell sell sell',
 'trump forev chang american polit',
 'kerri advis mari harf twitter fight iran nuke',
 'role us nato eu relat china manlio dinucci',
 'daili mani african american unenthusiast settl hillari clinton',
 'peopl come recent berni sander ralli',
 'trump presid mean world countercurr org',
 'fleec congress grill kerri obama offici iran nuke deal',
 'page hack wikileak email teach us hillari clinton',
 'comment break cdc block testimoni senior scientist blew whistl sever medic malpractic cdc accus block testimoni senior scientist new york malpractic injuri lawyer blog',
 'fox news admit made stori hillari indict foundat',
 'repudi media',
 'buchanan smash cnn shill',
 'imposs happen cub win world seri ye hillari clinton like indict',
 'america elect gullibl shatter david keran',
 'anderson cooper absolut own kellyann conway fbi clear hillari video',
 'schlong nyt fbi reopen hillari probe thank anthoni weiner',
 'american realli think elect coverag',
 'exclus sieg islamabad',
 'fix nbc affili accident post elect result week earli hillari win presid trump',
 'lynch school wingnut right tri fail wound obama ag nomine',
 'ye ted cruz could win',
 'build wall hand small nyc anti trump protest stream live',
 'trump advisor tri pivot fishtail',
 'christian drop none soar new religion portrait',
 'comment brother clinton campaign chair activ foreign agent saudi arabian payrol marlen',
 'insid deliber hillari clinton campaign launch',
 'american express disown pink floyd singer roger water pro palestinian view',
 'clinton condemn trump chicago violenc',
 'franc grow debat speech protect',
 'presid elect donald trump first televis interview sinc elect inform',
 'north carolina hillari support brag facebook vote multipl time',
 'russia react un aid chief aleppo kill zone remark',
 'repres govern thugocraci',
 'gay right religi liberti american',
 'rand paul stall ted cruz seek pick support among libertarian',
 'dream come true hillari clinton wall street journal editori board rip ted cruz',
 'obama press putin strike ukrain peac deal',
 'trumka disappoint obama warn hillari',
 'pro palestinian propaganda lower standard truth america',
 'wingnut death grip congress paul ryan control hous gop',
 'lift weight could ward dementia make smarter',
 'peopl excit christma advert told rest human cultur',
 'state depart warn possibl terror attack south africa',
 'lost iraq',
 'pope franci implor congress accept immigr',
 'poll trump gain iowa still domin new hampshir',
 'rand paul goe senat floor protest nsa spi measur',
 'china airport secur robot give electroshock',
 'obama detail disappoint netanyahu first post elect comment',
 'wikileak neera tanden anoth ring endors hillari realli',
 'realiti check first clinton v trump presidenti debat',
 'doomsday elect',
 'john kasich advic women prevent sexual assault avoid parti lot alcohol',
 'system set boehner failur',
 'gay marriag victori suprem court trigger backlash',
 'rode best jess jackson mount fight pipelin leonardo dicaprio rescu',
 'mccarthi drop speaker race hous ask want job video',
 'democrat republican tight race iowan prepar caucu',
 'iran best outcom keep negoti without reach deal',
 'nazi fli saucer perman base antarctica',
 'break man brag facebook vote time reveal',
 'furiou parent slam damag bbc sex chang show aim six year old',
 'trump famili say trump brand damag',
 'rand paul flatlin',
 'nurs chri christi quarantin ebola goe governor vaccin',
 'paul ryan donald trump coexist within republican parti',
 'cruz copi border wall trump say',
 'john oliv america increasingli segreg school rare equal way video',
 'rise mandatori vaccin mean end medic freedom',
 'scientist fascin lake sea enter never come watch',
 'jeb bush lose tv ad edg marco rubio',
 'russia india discuss fgfa advanc fighter su mki upgrad',
 'real polic race problem divers forc white resent america persist divid',
 'suprem court cannot hide obamacar',
 'break ted cruz call special prosecutor investig hillari truthfe',
 'poll hillari clinton berni sander top trump',
 'donald trump revok washington post press access video',
 'real reason obamacar come unglu',
 'jeb bush avoid jon huntsman',
 'reviv clinton email scandal kill slew new fact record time',
 'iraq sky darken islam state torch oil',
 'new yorker fight overturn ballot selfi ban',
 'poll find ben carson knock donald trump top spot nation',
 'glad surpris palestinian reaction netanyahu win',
 'georg w bush ethic lawyer file complaint fbi director jame comey',
 'netflix ceo tv futur includ hallucin pill',
 'ernst trump stop name call',
 'comment elect beammeupscotti',
 'debat duke say usa becom banana republ',
 'five fbi field offic probe clinton chariti ad fuel fire',
 'white hous gop fail put point board',
 'daili presid hillari clinton lose way could lose',
 'democrat want berni want berni',
 'podesta wiki leak prefer muslim christian',
 'critic pounc madelein albright exhort women back clinton',
 'clinton doubl disput claim fbi found email remark truth',
 'clinton haiti develop plan succeed disappoint',
 'cours facebook bias real problem admit',
 'tax calcul feder debt',
 'trump advis remain split far move toward middl',
 'clinton final stretch win anti trump conting may best play',
 'australian taxpay charg million donat corrupt clinton foundat',
 'vatican end scrutini u nun',
 'clinton email scandal took root',
 'jew blame holocaust hous lord event',
 'disappear middl elector way less moder past primari',
 'hanniti wikileak proven everyth conspiraci theorist said true',
 'russia success test first ever hyperson weapon',
 'hulk actor mark ruffalo join stand rock protest dapl',
 'ap fact check republican debat fact',
 'drop incom inequ',
 'walmart goe grain obama america new thanksgiv ad',
 'senat make histori confirm loretta lynch u attorney gener',
 'manhunt escap killer expand vermont',
 'path total dictatorship america shadow govern silent coup',
 'youth day elect anoth world possibl',
 'physic gold demand fear',
 'protest charg shoot offic ferguson',
 'comment u war iran alreadi begun',
 'locker room talk lock talk',
 'gop brace trump loss roil refus accept elect result',
 'one old vh tape may worth',
 'obama trump unfit serv presid',
 'pope franci met kim davi matter fight religi freedom video',
 'studi phytochem found broccoli cauliflow attack prostat cancer cell',
 'david duke win louisiana senat debat landslid despit blm riot',
 'pari tragedi could shake race',
 'hillari clinton radioact sot',
 'first gop debat six thing look charleston',
 'black hawk crash florida human remain found',
 'video creepi clown get pistol whip',
 'vision thing inform',
 'drudg koch soro bezo non politician determin next presid',
 'way know',
 'obama putin outlin compet vision syria',
 'comment polic offic wife caught fake robberi scheme frame black live matter cat vagina nasti woman',
 'gop lose walmart',
 'suprem court decid weigh transgend right',
 'hillari clinton charg obstruct justic could go prison year',
 'top secret email clinton server discuss drone program may refer classifi info',
 'miracl man metaxa vs close mind close univers',
 'obamacar premium spike averag',
 'collect conscious individu gone',
 'obama gun control emot evolut',
 'scientist found insid year old pot chang histori',

In [33]:
corpus[1]

'watch exact moment paul ryan commit polit suicid trump ralli video'

In [34]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3982, 3909, 1625],
 [90, 4879, 968, 2372, 1205, 2644, 2478, 3886, 4454, 3910, 3254],
 [1318, 225, 3696, 1374, 2708],
 [326, 2627, 841, 2528, 2256, 2679, 1068, 2450],
 [4242, 3654, 349, 3149, 1451],
 [4742, 3942],
 [3407, 4099, 90, 1211, 4994, 3509],
 [4764, 3714, 364],
 [1255, 3140, 4454, 4977, 3816, 1360, 4258],
 [4108, 1573, 134, 3654, 3254, 1572, 2917, 1682, 157],
 [4725, 4977, 2362, 2902, 4710, 892, 3909, 4977, 2683],
 [3087, 4454, 2741, 650, 3650, 200, 1428, 1630, 563, 443],
 [4960, 1034, 1791, 3386, 4046, 618, 2904, 1779, 3254],
 [958, 137, 2226, 1124, 120],
 [4454, 3427, 1964, 115],
 [727, 4504, 666],
 [3650, 2350, 4991, 3909, 811, 1682, 3503, 3098, 3324],
 [3909, 4977, 3215, 649, 137, 671, 1879, 4247, 1092, 136, 3696, 322, 2904],
 [4108, 2165, 4991, 688],
 [1504, 1171, 2376, 3859, 215, 1234, 137],
 [1060, 916, 4454, 2853, 4325, 2469],
 [3796, 50, 945, 787, 1838, 4732, 4355, 2758, 4996],
 [3909, 4977, 134, 2800, 3868, 2373, 467],
 [3654, 1425, 2850, 2776, 1532, 861, 2851, 246],
 [4719, 2660, 440],
 [145, 4454, 2585, 4088, 3674, 1811, 3650, 1634],
 [2392, 2549, 4977, 3056, 2135, 134, 666],
 [3087, 4454, 3200, 2683, 2997, 4118, 3506],
 [2811, 2784, 3087, 4454, 2683, 981, 1874, 2902, 2403, 50, 703, 2379, 4657],
 [1428, 120, 3539, 3179, 1428, 4248, 1484, 552, 4242, 1417, 1826],
 [2851, 2599, 1665, 4322],
 [1033, 1327, 1368, 3087, 3423, 3233, 3233, 951, 3606, 3254],
 [1538, 2900, 3131],
 [1236, 2939, 1278, 1690, 4710, 726, 3832, 3165, 2465],
 [173, 3453, 1125, 3958, 161, 2250, 594, 35, 2768, 3023, 1616, 3200],
 [3265, 3778, 593, 1730, 539, 1047, 4752, 2571, 2928, 137, 2189, 2904, 568],
 [331, 3023, 1675, 1180, 1789, 4251],
 [3087, 3430, 3909, 4454, 1253, 2896],
 [3198, 4036, 2043, 496, 4977, 537, 313],
 [3909, 3242, 4179, 1748, 2577, 4282],
 [3294, 3242, 2611, 2461, 4986],
 [331, 3427, 3783, 1418, 2691, 1780, 2341, 4682],
 [4372, 1815, 1720, 4558, 40, 2836, 3499, 723, 1249],
 [4490, 1180, 1648, 4454, 4734, 2324, 304, 1817, 927],
 [4208, 1791, 2994, 4977, 1225, 706, 4454, 4731, 4949],
 [1652, 1835, 24, 1145, 4460, 2011, 649, 2321, 2814],
 [4991, 134, 277, 2667, 1406, 11],
 [1425, 3593, 2647, 2540, 4362, 2851, 594, 816, 3832, 978],
 [215, 2276, 3242, 3098, 874, 576, 2469, 2137, 3683, 334, 2608, 2994, 3650],
 [3161, 1397, 2043, 2562, 272, 2445, 4003, 3958, 4977, 786, 1825, 3342, 1027],
 [3458, 2478, 3937, 2054, 1521],
 [145, 886, 2529, 2663, 2411, 2262, 3126, 2281, 3254],
 [4225, 4534, 2646, 3315, 313, 2155],
 [1132, 1711, 4461, 4055, 701, 4191, 2430, 412],
 [3654, 3619, 1582, 3470],
 [1124, 2302, 432, 3285, 4362],
 [2727, 3116, 2379, 1583, 4408],
 [1515, 3149, 756, 3257],
 [4814, 851, 588, 3668, 1230, 500, 1779, 133, 428],
 [3087, 4454, 3909, 4977, 1279, 1360, 1813],
 [2784, 727, 2618, 4257, 863, 4372, 161, 2761, 3261, 4814, 4814],
 [3731, 134, 1125, 3618, 2478, 3958],
 [3909, 4977, 435, 3391, 3661, 104],
 [3619,
  2113,
  1683,
  882,
  272,
  876,
  4554,
  4977,
  2683,
  3284,
  2372,
  1205,
  3692,
  3751,
  874,
  2862,
  3324],
 [3909, 4977, 2363, 3247, 4966, 3315, 4435],
 [4021, 1621, 1726, 4454],
 [254, 2871, 727, 331, 1338, 3458, 1180, 2366],
 [2864, 1177, 3591, 621, 908],
 [2043, 3140, 1196, 1321, 2474, 3916, 4362, 540, 2450, 4814],
 [2955, 1008, 3909, 2236],
 [3958, 1332, 3249, 578],
 [2324, 4086, 3878, 3245],
 [2851, 2111, 3768, 2193, 1964, 4597, 3087, 4454],
 [326, 2392, 3548, 3178, 3725, 1823, 4827, 1968, 917, 2004, 2478, 442],
 [4138, 4438],
 [1657, 3213, 4066, 140, 1626, 785],
 [1177, 3593, 1614, 3654, 3121, 2510],
 [426, 3261, 4777, 4827],
 [4505, 1318, 4394, 1428, 350],
 [3911, 1304, 3238, 3362, 1315, 4635, 876, 1027],
 [326, 2392, 2667, 831, 1013, 2841, 3100, 2476, 4766],
 [47, 2503, 3654, 349, 4965, 3149, 1980, 3245],
 [4138, 514, 4251, 4991, 851, 1343, 4413],
 [3589, 2156, 2241, 4291, 134, 1476, 3020, 2085, 1789],
 [3024, 1318, 715, 3118, 2403],
 [856, 1669, 637, 145, 3958, 2197],
 [17, 3233, 3751, 874, 4454],
 [2193, 1964, 4332, 2698, 3958, 1425, 3661],
 [4991, 2262, 281, 4413, 728, 4984, 137],
 [326, 2392, 225],
 [3361, 2851, 2683, 4500, 1634, 643],
 [3644, 2989, 2389, 1074, 3565, 1074, 3995],
 [71, 1106, 733, 329, 3018, 3958, 4488, 4977, 3254],
 [3909, 4977, 326, 2392, 4695, 4413],
 [565, 4814, 3947, 1013, 456, 1285, 4374, 3285, 469, 4362],
 [1510, 4225, 1604, 3027, 914, 4460, 3572, 683, 557, 2317, 3254, 764],
 [3791, 3027, 3725, 134, 666, 3249, 3482],
 [2751, 439, 4248, 986, 2328, 50, 1638],
 [3530, 2528, 4454, 3213, 4021, 1964, 2851, 568],
 [4991, 2451, 688, 3567, 3317, 4699, 4762, 4986],
 [2193, 1964, 178, 2193, 1964],
 [182, 728, 3272, 2322, 4838, 4630, 3651, 1109],
 [2251, 3937, 2392, 3923, 2679, 4402, 1932, 3567, 3725, 874],
 [4501, 1144, 2190, 3074, 3912, 1006, 2848],
 [2043, 2925, 3403, 4977, 876, 362, 4045, 2255, 1315],
 [1330, 2772],
 [1535, 3554, 356, 3352, 4701, 3254],
 [1682, 4263, 728],
 [3326, 802, 3589, 4454, 790, 2565],
 [790, 1318, 29, 4222, 3254, 2133, 4539, 3857, 831, 2904, 1609, 1391, 835],
 [4641, 4977, 4206],
 [456, 1281, 3886, 342, 2971],
 [4420, 500],
 [2465, 4673, 2400, 885, 3150, 3942, 2552],
 [1458, 2210, 4930, 3909, 605, 4454, 2210, 1413],
 [245, 1286, 3411, 2416, 3261],
 [742, 977, 1606, 2508, 4136],
 [922, 4454, 3725, 2450, 442, 4977, 1413],
 [4716, 299, 2296, 619, 1900, 3554, 3238],
 [728, 3837, 3565, 4965, 568],
 [4991, 469, 4762, 344, 2085, 165, 4562, 4964],
 [326, 3859, 3895, 3377, 4259, 876, 3024, 1135, 1451],
 [281, 4460, 3024, 2360, 3981, 591],
 [2820, 1107, 4072, 2463, 4938],
 [368, 4626, 3302, 2450, 2465, 4046, 1789, 3958, 500, 4065, 1385, 4600],
 [3847, 3294, 4072, 4877, 64, 3118, 1846, 568],
 [3213, 4021, 2235, 3284, 3027, 1125, 3579, 4454],
 [4064, 165, 1171, 1996, 4991, 2416, 1285, 2465, 1054, 4965],
 [3939, 3685, 4454, 3238, 2465, 3874, 240, 2407, 2085],
 [4577, 2646, 1057, 3289, 3654, 4096, 770],
 [417, 2087, 2717, 514, 1813, 1712, 2302],
 [3027, 1789, 632, 948],
 [1065, 4454, 2127, 1480],
 [4454, 981, 3238, 2531, 3725, 4894, 1413, 2085, 1789],
 [272, 2165, 4977, 666, 2165, 1285, 1938],
 [3539, 4532, 4166, 4454, 35, 4758, 4627, 990, 2696],
 [3051, 614, 1820, 50, 4887, 1013, 2362, 3426],
 [4247, 1537, 3458, 215, 3087, 4454, 540, 3628, 2219, 4285],
 [509, 2698, 1968, 1988, 3589, 4282, 563, 1546, 4251],
 [890, 3650, 3661, 1498, 4082, 4498],
 [3737, 1198, 37, 2306, 3539, 4454, 4465, 2627],
 [4752, 2448, 4505, 2744, 3118, 1789, 3958],
 [4101, 361, 2704, 2043, 496, 225, 3909, 2984, 3783, 1418, 4488],
 [3118, 1403, 2540, 2878, 4977, 4966, 2400, 563, 4402],
 [4454],
 [4108, 861, 4958, 2878, 3714],
 [2475, 109, 752, 4466, 1791, 1057, 3131, 2887, 3668, 3200, 3576],
 [1830, 55, 2283, 533, 2596, 55, 4138, 2110, 2539],
 [2043, 1873, 1789],
 [3087, 4454, 1413, 4460, 2033, 3958, 3572, 331, 1884, 3958, 1729],
 [4693, 4700, 959, 2585, 650],
 [2977, 4991, 297, 2823, 868, 1825, 3342, 1987, 4454],
 [3619, 2891, 4454, 2627, 3296, 3249, 3909, 1622],
 [4027, 2904, 3027, 157, 1789],
 [2598, 2608, 688, 1923, 995, 711, 4454, 4977, 4989],
 [439, 3565, 4823, 2043, 4713, 4977, 876, 3247],
 [4991, 2975, 757, 2101, 764, 2627, 4108, 1682, 861],
 [4977, 540, 3958, 2392, 359],
 [4924, 2405, 3752, 1425, 4965, 4300, 1690, 861],
 [4014, 1826, 3816, 3999, 4986, 3380, 4362],
 [2717, 1960, 4138, 3105, 2259, 3254, 4977, 2683],
 [1827, 4362, 2085, 165, 3324, 2526, 4878],
 [2219, 2011, 2509, 629, 4250, 4460, 4377, 3210],
 [3254, 3100, 1726, 1733, 4814, 1779, 133, 3176, 173],
 [489, 2245, 4379, 2980, 1638, 1054, 3396],
 [4400, 2465, 563, 4372],
 [4108, 4939, 1682, 1201, 585, 861, 1124, 69],
 [3619, 599, 3526, 599, 3526, 2665],
 [3504, 3165, 4118, 2626, 1873, 469, 397, 3579, 2403],
 [326, 2392, 4434, 811, 1306, 1648],
 [3274, 4294, 3214, 732, 2667, 2181, 29, 2551, 2295, 277, 1914],
 [4454, 3654, 3470, 2517, 1537, 3737, 4434, 3768, 3926, 1480, 2952],
 [2531, 3254, 2011, 4991, 540, 134, 3458, 538, 855, 688, 4764, 1027],
 [4641, 4991, 2, 2851, 2400, 4251],
 [1428, 120, 3539, 3179, 715, 3087, 4429, 2427, 1263, 2100, 4893, 790, 1826],
 [1827, 3589, 2618],
 [50, 2863, 1095, 22, 417],
 [134, 1451, 443, 1480],
 [1255, 3140, 3909, 4977, 2262, 4965, 2841, 3487],
 [2112, 4977, 4502, 2411, 3143, 4500, 786, 1789],
 [4854, 727, 331, 3832, 4539, 2269, 2035, 3453, 855],
 [18, 371, 1018, 2966, 4514, 2577, 4282],
 [4108, 476, 3654, 2446, 3388, 618],
 [2228, 3087, 4454, 977, 1413, 4977, 715, 4184, 3512],
 [1345, 3731, 4138, 921],
 [4860, 2372, 1205, 165, 2400, 277, 277],
 [326, 2392, 3859, 2259, 1413, 1968, 3832, 1968],
 [4259, 4991, 1690, 861],
 [3386, 1441, 3317, 727, 3023, 1923, 4994, 4313, 4692, 3458, 4249],
 [4235, 672, 2324, 89, 802, 1813],
 [4808, 2903, 673, 2689, 154, 1277, 1013, 3544],
 [4178, 1068, 1171, 603, 3027, 3131],
 [1789, 3958, 4677, 2716, 4661, 4965, 4594, 1823],
 [2698, 4454, 4133, 1007, 3257, 2186, 3654, 3239],
 [225],
 [1452, 3380, 2238, 4261, 2740, 2698, 3219],
 [1185, 763, 4594, 2345, 3832, 1306, 1657, 3213, 134, 2373],
 [3003, 2345, 4318, 2470, 584, 4279, 47, 870, 3741, 2379, 4777, 3845],
 [436, 2871, 602, 2465, 3143, 1694, 2253, 1456],
 [2392, 3910, 2627, 514, 4977, 2679, 876, 4259],
 [697, 3589, 861, 2924, 119, 124, 1476, 4350],
 [957, 3131, 3315, 2334, 69],
 [4454, 1901, 2080, 3565, 727, 134, 998, 2088, 3160],
 [3295, 1227, 3242, 339, 237, 469],
 [145, 4454, 470, 4594, 1650, 613, 571, 2915, 2139, 645],
 [3458, 1704, 3239, 2133, 727, 1873],
 [473, 603, 4072, 3909, 4977],
 [3909, 1923, 1253, 2886, 3576, 4118, 2683, 529],
 [4977, 4597, 4454, 4501, 323, 3020, 1072, 760, 4282, 4472, 1871],
 [416, 4460, 2766, 2181, 3179, 4640, 28],
 [4986, 362, 4394, 715, 4211, 2174],
 [29, 1416, 4150, 1992, 3265, 1090, 3539, 565, 4814, 427, 4029],
 [4752, 1754, 2302, 533, 2735, 277],
 [4752, 4150, 3295, 2518, 3003, 2472, 395],
 [818, 136, 818, 4701, 2928, 137, 2189, 2904, 568],
 [1657, 3213, 2577, 4282, 540, 4248, 4912, 2939, 4369],
 [3024, 2235, 1900, 3118, 4195],
 [314, 3553, 3909, 4977, 2853, 243, 4546, 1789],
 [4734, 2701, 3318, 3251, 884, 4838, 2226, 4374, 3285, 4362],
 [4946, 4559, 3900, 3131],
 [1102],
 [4454, 3612, 1263, 3654, 1124, 4279],
 [568, 861, 4965, 4877],
 [3577, 3105, 876, 4930, 2738, 3874, 3596, 347, 4362, 2991],
 [2266, 2658, 3792, 4859, 40, 2049, 4249],
 [4454, 4063, 3880, 4737, 4074, 281],
 [2540, 3923, 2851, 4454, 243, 683],
 [2085, 3186, 2586, 332, 1776, 552, 3380],
 [4108, 867, 2370, 3018, 2851],
 [4977, 2031, 1445, 2465, 3164, 2657],
 [3087, 4454, 2851, 2295, 120],
 [3619,
  4778,
  3515,
  1071,
  4887,
  1454,
  1480,
  2425,
  1813,
  4794,
  3324,
  1071,
  1625,
  4538,
  1071],
 [2288, 3213, 2859, 3668, 2139, 3909, 2698],
 [18, 371, 2568, 4717, 4930, 964, 2717, 1960],
 [2740, 2478, 4804],
 [3909, 2989, 2657, 1456],
 [3131, 3449, 3490, 3472, 3751, 874],
 [4977, 3650, 1413, 2540, 1410, 827, 3539, 2392, 728, 3452],
 [3909, 529, 4454, 1297, 2376, 4778, 3926, 2627, 2085],
 [4454, 3238, 4991, 4082, 2085, 4545, 3654, 1867, 3181],
 [1509, 890, 1621, 2595, 3961, 509],
 [2955, 540, 1369, 4796, 3343, 439, 601, 3210, 1007, 3909, 2683],
 [1606, 258, 3049, 2085, 1456, 4794, 3362, 3844, 1177],
 [137, 2749, 3905, 3027, 2465, 926, 2085, 1370, 1171, 137],
 [3118, 4930, 4454, 1604, 4147, 818, 688, 3118],
 [2784, 3342, 3938, 2540, 1177, 4700, 2035, 2853],
 [3654, 2658, 2844, 2551, 1702, 894, 4382, 4162, 443],
 [4977, 2392, 1285, 4454, 1230, 500],
 [3294, 509, 3770, 1293, 4912, 165, 1928, 1293],
 [3654, 3118, 3909, 4977, 654, 876, 944, 1451, 1619],
 [4454, 1060, 3016, 4946, 134, 1355, 3732, 3783],
 [319, 224, 137, 4725, 2654, 3063, 219],
 [3087, 4454, 265, 811, 1034, 1928, 861, 2351, 2351, 2351],
 [4454, 2313, 3200, 3458, 2478],
 [1318, 1996, 2254, 2287, 841, 64, 4108, 2041],
 [3921, 2085, 4619, 726, 2407, 596, 993, 1512],
 [1628, 3444, 1338, 3458, 3484, 4364, 3909, 4977],
 [4737, 4860, 2093, 326, 2392, 3910],
 [4454, 2698, 4147, 1124, 2678, 3294],
 [1680, 4251, 100, 1318, 4991, 3595, 4108, 2041, 861],
 [3575, 1054, 272, 876, 4540, 2085, 3909, 4977],
 [3619,
  3911,
  760,
  4986,
  552,
  4569,
  1362,
  1744,
  2475,
  3917,
  4729,
  599,
  760,
  1285,
  4986,
  552,
  4569,
  1362,
  3654,
  349,
  599,
  16,
  4557,
  4282],
 [2841, 2904, 3317, 1604, 4192, 3909, 4402, 4502],
 [1814, 3565],
 [4371, 1241, 3791, 4848],
 [4130, 4641, 4379, 1413, 1124, 3533, 806, 3909, 4977, 688, 4402],
 [137, 1789, 2231, 3381, 1458, 4471],
 [2707, 64, 2059, 625, 4653, 2580, 2043, 4214, 3909, 3254],
 [259, 4824, 2043, 35, 3909, 3403, 1802, 854, 1253],
 [3458, 613, 2878, 1789, 1172],
 [3361, 1384, 2184],
 [1130, 543, 4465, 4586, 1759, 1789, 385, 818, 3105, 3909, 1413, 2698, 4454],
 [2871, 2350, 4788, 277, 1068, 344, 1864, 4991, 2366, 2076],
 [806, 2193, 1964, 1832, 1413],
 [879, 3783, 426, 4480, 418, 145, 4454, 3541, 396, 957],
 [4454, 1746, 1068, 3054, 4935],
 [1827, 4206, 2627, 1546, 3654, 4362, 2365],
 [3619, 456, 4977, 2683, 2476, 4915, 2577, 2562, 4002, 4304, 2966, 2969],
 [2599, 3126, 3909, 4977, 2683, 362],
 [3458, 296, 1565, 1030, 3913, 1344, 1110, 29, 1683, 4033, 3421],
 [4977, 4884, 4454, 4870, 500],
 [1227, 701, 568, 2262, 1648],
 [2698, 1789, 3087, 4454, 331, 1437, 173, 2515, 1789, 1456],
 [2128, 4827, 3909, 2627, 3865, 621, 3249, 604, 3131],
 [2465, 432, 826, 154, 1360, 1826, 4887, 1140, 287],
 [1361, 2403, 4438],
 [2735, 277, 2526, 3696, 3458],
 [3018, 2372, 2522, 2193, 1964, 4088, 4066, 2627, 728, 2144],
 [3786, 4860, 541, 3909, 4977, 3783, 1418, 645, 455, 3176, 4683, 2193, 1964],
 [4991, 154, 3939, 2942, 1143, 4369, 861],
 [2168, 810, 4991, 2450, 3909],
 [1683, 4033, 4757, 811, 490, 2324, 137],
 [4788, 1813, 4243, 4251, 2372, 1205, 927, 3342, 2851],
 [4044, 4382, 1832, 668, 3026, 134, 1053],
 [4737, 865, 1983, 470, 47, 3404, 3651, 652],
 [3832, 2448, 2450, 3944, 469, 4362, 1823, 2436],
 [3548, 4986],
 [1308, 1190, 2976, 4251, 451, 1286],
 [3118, 4454, 4162, 2362, 4188, 206, 3654, 4729],
 [3018, 2372, 4521, 1425, 3938, 3541, 2848, 3210, 964],
 [596, 3738, 4248, 3662, 2751, 2709],
 [4991, 3020, 810, 742, 331, 1759, 1789, 3619],
 [272, 1681, 4771, 1125, 2654, 140, 3909, 613],
 [3239, 3140, 331, 4977, 783, 4454, 4072, 568],
 [2940, 1789],
 [3024, 2235, 4868, 727, 2616, 998, 2088, 4145, 3294, 3350, 1120],
 [3677, 4408, 1338, 1007],
 [2735, 3577, 2565, 3751, 874, 1285, 2947],
 [2899, 4704, 4635, 1473, 4339, 64, 1835, 1801, 1068, 1383],
 [309, 4206, 1014, 3593, 3342, 3760, 3242, 2110, 3254],
 [4965, 1177, 2449, 3593, 3855, 2226, 4644],
 [4108, 4704, 2600, 4966, 4223, 1546, 3937, 861],
 [3915, 4952, 2551, 1645, 40, 4660],
 [3911, 683, 3865, 621, 3249, 3131, 4554],
 [2548, 480, 1901, 255, 2476, 334, 3200, 4930, 1517, 986, 4460, 3572],
 [4454, 313, 3238, 4454, 300, 255],
 [3018, 2372, 3370],
 [1254, 1185, 763, 2750, 4273, 4521, 3334, 1071],
 [2372, 1205, 3087, 4454, 4472, 4820, 1177, 3294],
 [1964, 37, 3319, 3783, 4454, 3238],
 [3024, 539, 137, 1641, 3149, 2350, 261, 1439, 958, 3254],
 [3556, 3845, 1071, 4147, 2181, 4729, 4878],
 [1362, 217, 2093, 4032, 1614, 4423, 4860, 90],
 [1657, 3213, 4594, 1405, 3470, 4672, 81, 4021],
 [2465, 842, 4394, 407, 552, 775, 1252, 2346, 1822],
 [4372, 4814, 3593, 2004, 3307, 2585, 1825, 169, 137, 4779, 533],
 [3751, 874, 2657, 3237, 3792],
 [3911, 2193, 1964, 2667, 4732, 2158, 3247, 3909, 1027],
 [3118, 3909, 4977, 326, 2392, 926, 4454],
 [3087, 4454, 1414, 3003, 1759, 154, 1932, 3254],
 [4372, 2503, 3792, 4860, 1749],
 [1657, 3213, 4145, 4363, 1408],
 [3500, 4977, 876, 1117, 4887, 4585, 3654, 1255, 2814, 3131],
 [4986, 3689, 1207, 3144, 3832, 872, 3922],
 [3654, 4989, 64, 4753, 4144, 4711, 4325],
 [3118, 4464, 4359, 2936, 1886, 3087, 4454, 926, 1846, 119],
 [3882, 3618, 4033, 1608, 742, 1413],
 [106, 3056, 3213, 4847, 4557, 209, 683, 2043, 496, 3819, 4064],
 [4156, 2328, 1405, 2537, 3165, 4901, 4941],
 [4581, 4454, 3958, 960, 2667],
 [3619, 1789, 4596],
 [568, 2210, 3238, 3942, 727, 1760, 4057],
 [47, 2043, 3599, 1729, 3403, 4977, 1683, 3470, 924, 4710],
 [1825, 3342, 2851, 344, 2693, 4147, 3176],
 [1628, 2698, 3909, 4977, 4594, 958, 1832, 4594],
 [4965, 3242, 326, 3242, 326],
 [1135, 3363, 4259, 1679, 2469, 1827],
 [3567, 170, 1133, 992, 2346, 727, 2539, 4977],
 [4977, 4792, 1212, 3160, 2043, 2836, 876, 287, 2324],
 [4977, 2370, 300, 540, 4552, 810],
 [1527, 621, 3826, 4372, 2004, 3317],
 [2042, 2784, 3264, 614],
 [4454, 1996, 4789, 1230, 4294, 3315, 3440, 2740],
 [4977, 1476, 3131, 1413, 145, 4454, 1439, 4673, 4704, 3655],
 [2930, 2011, 2608, 629, 3807, 2080, 4977, 4502],
 [4536, 2181, 2120, 2219, 4180],
 [4977, 876, 1117, 1297, 509],
 [3147, 245, 3532, 3342, 3946, 2464],
 [2642, 2740, 323, 958, 3988, 1603, 679, 3149],
 [4071, 272, 3996, 2376, 417, 3541, 265, 541],
 [2465, 2479, 618, 331, 3023, 4638, 4263],
 [3085, 2497, 4334, 55, 3999, 1779, 133, 3541, 1098],
 [827, 1255, 3140, 1177, 568, 1255],
 [4206, 4633, 99],
 [3076, 4521, 896, 4991, 137, 3654, 115, 3470],
 [1425, 134, 4249, 313, 254, 2871, 2219, 1977, 2884],
 [643, 1277, 1887, 2925, 1633],
 [4509, 4017, 2193, 137, 3579, 2403, 71, 733],
 [247, 3958, 1789, 1125, 1124, 3944],
 [3426, 2379, 3416, 1625],
 [3541, 2608, 3261, 1729, 4815],
 [3619, 2219, 120, 4108, 1145, 1056],
 [4321, 1499, 157, 2225, 157],
 [2851, 233, 4454, 900, 4373, 297, 451, 1789, 385],
 [3027, 3572, 1718, 543, 4673, 2326],
 [4991, 4454, 2720, 3004, 2698],
 [1308, 1190, 1514, 1176, 399, 1451, 64, 2526, 4878, 3254],
 [2658, 312, 2836, 2192, 1317, 4362, 695, 4624, 2222],
 [1458, 2210, 1413, 2809, 1425, 568, 369, 2316, 2795, 4421],
 [3696, 54, 1832, 3506, 3593],
 [3909, 4977, 2012, 4944],
 [331, 2851, 568, 986, 4247, 890, 2863],
 [4465, 4895, 3355, 2357, 3651, 4789, 2836],
 [3254, 2229, 219, 4138, 4418, 804],
 [4958, 4247, 1456],
 [2428, 220, 3540, 2619, 4710, 2238, 3314, 509, 2698],
 [958, 215],
 [4991, 3939, 4941, 2808, 4958, 1480],
 [3619,
  4814,
  1729,
  2474,
  811,
  2038,
  1372,
  294,
  4938,
  4465,
  957,
  1451,
  1328,
  1483,
  154,
  1180],
 [2851, 4594, 3076],
 [3751, 874, 3702, 4635, 493, 277],
 [3909, 4977, 2608, 1940, 4752, 1832, 225, 4808, 4460],
 [926, 1720, 876, 4977, 2569, 4394, 1124, 4246, 4673, 281, 3049, 2212],
 [2161, 683, 56, 4597, 1515, 448, 1515, 811],
 [3792, 3633, 1009, 444],
 [3277, 4200, 3315, 3828],
 [4991, 538, 927, 3535, 1624],
 [1362, 2836, 2599, 4460, 3572, 2716, 3200, 4249],
 [3112, 3975, 1177, 4188, 2465, 3792, 3016],
 [4454, 4934, 3666, 3654, 4729],
 [2851, 4072, 4877, 2888, 926, 1720, 4977, 876, 1476, 3958, 2362, 4644],
 [2465, 4752, 2448, 3937, 4814, 861],
 [1179, 3238, 4200, 1810, 3832, 1451, 4710, 3426, 4372],
 [2851, 2755, 250, 220, 601, 2077, 3857],
 [4763, 3525, 3780, 4454, 4977, 485, 4072, 4066],
 [4454, 4977, 4938, 1515, 663],
 [18, 371, 728, 4991, 3276],
 [3909, 1879, 1861],
 [3795, 4912, 4233, 266, 954, 909, 3131, 4801, 3369],
 [2392, 4454, 1699, 1413, 3605, 2266, 3149, 4454, 4066, 2558],
 [4977, 2392, 3233, 2234, 4965, 568],
 [3456, 4033, 1779, 2220],
 [3651, 4789, 4326, 322, 1806, 1709, 3961, 65, 3595, 3238],
 [2085, 3595, 4313, 469, 2138, 2701, 3696, 4362, 3051],
 [715, 3880, 4887, 4033, 3027, 3027, 1713, 4789, 593, 1606],
 [3909, 2478, 1362],
 [3482, 2698, 1015, 3545, 3541, 4223, 4223, 3254, 2772, 4623],
 [4977, 4066, 331, 2850, 712, 140],
 [2844],
 [4991, 1480, 120, 2296, 2181, 2698],
 [3483, 4835, 497, 4695, 3910, 514, 4814, 2701, 1729, 1887, 4521],
 [1425, 552, 2165, 728, 4773, 1835, 2316, 4991, 2101, 3870],
 [3619,
  4343,
  2325,
  1604,
  142,
  2527,
  4343,
  2325,
  1604,
  142,
  2527,
  3277,
  1091,
  2215,
  2904,
  1278,
  2325,
  2215,
  2904,
  1278],
 [2085, 3488, 826, 3249, 2667, 2181, 4797, 3728],
 [732, 1073, 4464, 4454, 4594, 3982, 1177, 331, 3131, 3640, 3254],
 [3619, 1640, 4392, 3087, 3160, 4659, 3041, 3618, 1279, 59, 4566, 3754, 2478],
 [359, 5, 1428, 4136, 1776],
 [3654, 647, 4677, 1286, 3677, 3453, 1347, 3458],
 [137, 1100, 281, 4454, 2540, 3909, 281, 4594],
 [3565, 851, 1692, 3284, 3909, 4977, 781, 2374],
 [3832, 2448, 3317, 3126, 1263, 3884, 2570, 4108, 861],
 [2219, 4285, 3470, 2110, 4701, 4853, 600],
 [3909, 4977, 1006, 1413, 3000, 3832, 326, 2392, 3859, 3215, 917],
 [1124, 120],
 [4887, 3261, 2357, 4376, 3944, 2190, 3144, 469],
 [1125, 3958, 161, 4977, 537, 313],
 [2469,
  4579,
  4794,
  211,
  4706,
  824,
  4895,
  782,
  2667,
  857,
  3275,
  2262,

In [35]:
corpus[1]

'watch exact moment paul ryan commit polit suicid trump ralli video'

In [36]:
onehot_repr[1]

[90, 4879, 968, 2372, 1205, 2644, 2478, 3886, 4454, 3910, 3254]

### Embedding Representation

In [37]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3982 3909 1625 ...    0    0    0]
 [  90 4879  968 ...    0    0    0]
 [1318  225 3696 ...    0    0    0]
 ...
 [ 145 4454 3541 ...    0    0    0]
 [ 674 4991 4088 ...    0    0    0]
 [1657 3213 2168 ...    0    0    0]]

In [38]:
embedded_docs[1]

array([  90, 4879,  968, 2372, 1205, 2644, 2478, 3886, 4454, 3910, 3254,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [39]:
embedded_docs[0]

array([3982, 3909, 1625,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [40]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [41]:
len(embedded_docs),y.shape

(6335, (6335,))

In [42]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [43]:
X_final.shape,y_final.shape

((6335, 20), (6335,))

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [46]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=30,batch_size=64)

Epoch 1/30

67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9835 - loss: 0.0661 - val_accuracy: 0.7422 - val_loss: 1.0542
Epoch 2/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.9854 - loss: 0.0609 - val_accuracy: 0.7465 - val_loss: 0.9323
Epoch 3/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.9840 - loss: 0.0633 - val_accuracy: 0.7461 - val_loss: 1.0211
Epoch 4/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9830 - loss: 0.0640 - val_accuracy: 0.7418 - val_loss: 1.1222
Epoch 5/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - accuracy: 0.9861 - loss: 0.0574 - val_accuracy: 0.7418 - val_loss: 1.1099
Epoch 6/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.9875 - loss: 0.0514 - val_accuracy: 0.7461 - val_loss: 0.9006
Epoch 7/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9877 - loss: 0.0506 - val_accuracy: 0.7456 - val_loss: 1.1670
Epoch 8/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9882 - loss: 0.0493 - val_accuracy: 0.7346 - val_loss: 1.1714
Epoch 9/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.9901 - loss: 0.0447 - val_accuracy: 0.7374 - val_loss: 1.1966
Epoch 10/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9906 - loss: 0.0469 - val_accuracy: 0.7422 - val_loss: 1.1561
Epoch 11/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9875 - loss: 0.0504 - val_accuracy: 0.7394 - val_loss: 1.2316
Epoch 12/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9859 - loss: 0.0526 - val_accuracy: 0.7413 - val_loss: 1.1692
Epoch 13/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9915 - loss: 0.0394 - val_accuracy: 0.7284 - val_loss: 1.1744
Epoch 14/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9927 - loss: 0.0319 - val_accuracy: 0.7351 - val_loss: 1.3079
Epoch 15/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9932 - loss: 0.0283 - val_accuracy: 0.7394 - val_loss: 1.4137
Epoch 16/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9901 - loss: 0.0361 - val_accuracy: 0.7336 - val_loss: 1.3251
Epoch 17/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9920 - loss: 0.0326 - val_accuracy: 0.7308 - val_loss: 1.4241
Epoch 18/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9918 - loss: 0.0270 - val_accuracy: 0.7298 - val_loss: 1.5089
Epoch 19/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9908 - loss: 0.0284 - val_accuracy: 0.7355 - val_loss: 1.5193
Epoch 20/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9885 - loss: 0.0341 - val_accuracy: 0.7427 - val_loss: 1.3999
Epoch 21/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.9925 - loss: 0.0235 - val_accuracy: 0.7322 - val_loss: 1.5071
Epoch 22/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9941 - loss: 0.0164 - val_accuracy: 0.7298 - val_loss: 1.6604
Epoch 23/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9925 - loss: 0.0170 - val_accuracy: 0.7308 - val_loss: 1.6627
Epoch 24/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9936 - loss: 0.0162 - val_accuracy: 0.7284 - val_loss: 1.5986
Epoch 25/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.9948 - loss: 0.0123 - val_accuracy: 0.7312 - val_loss: 1.8042
Epoch 26/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.9927 - loss: 0.0172 - val_accuracy: 0.7370 - val_loss: 1.6264
Epoch 27/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9962 - loss: 0.0111 - val_accuracy: 0.7298 - val_loss: 1.8325
Epoch 28/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9960 - loss: 0.0125 - val_accuracy: 0.7279 - val_loss: 1.8666
Epoch 29/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9929 - loss: 0.0181 - val_accuracy: 0.7269 - val_loss: 1.7595
Epoch 30/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9903 - loss: 0.0235 - val_accuracy: 0.7312 - val_loss: 1.8005

### Adding Dropout

In [47]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [48]:
y_pred=model.predict(X_test)

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step

In [49]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_test,y_pred)

array([[1071,    0],
       [1020,    0]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5121951219512195

In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.51      1.00      0.68      1071
           1       0.00      0.00      0.00      1020

    accuracy                           0.51      2091
   macro avg       0.26      0.50      0.34      2091
weighted avg       0.26      0.51      0.35      2091

d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])