In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\CODING\PYTHON\NLP\9.LSTM\fake_or_real_news.csv")

In [5]:
df.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [6]:
df.shape

(6335, 4)

In [7]:
df.drop(columns=["Unnamed: 0"],inplace=True)

In [8]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [10]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [11]:
from sklearn.preprocessing import LabelEncoder

la=LabelEncoder()
df["label"]=la.fit_transform(df["label"])

In [12]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [13]:
## Get the Dependent features
y=df['label']

In [14]:
X.shape

(6335, 2)

In [15]:
y.shape

(6335,)

In [16]:
import tensorflow as tf

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [18]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [19]:
messages=X.copy()

In [20]:
messages['title'][1]

'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)'

In [21]:
messages

,title,text
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello..."
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T..."
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...
...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene..."
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...

In [27]:
#messages.reset_index(inplace=True)

In [22]:
messages

,title,text
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello..."
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T..."
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...
...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene..."
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...

In [23]:
import nltk
import re
from nltk.corpus import stopwords

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sinha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499
3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999
4000
4001
4002
4003
4004
4005
4006
4007
4008
4009
4010
4011
4012
4013
4014
4015
4016
4017
4018
4019
4020
4021
4022
4023
4024
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4035
4036
4037
4038
4039
4040
4041
4042
4043
4044
4045
4046
4047
4048
4049
4050
4051
4052
4053
4054
4055
4056
4057
4058
4059
4060
4061
4062
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4076
4077
4078
4079
4080
4081
4082
4083
4084
4085
4086
4087
4088
4089
4090
4091
4092
4093
4094
4095
4096
4097
4098
4099
4100
4101
4102
4103
4104
4105
4106
4107
4108
4109
4110
4111
4112
4113
4114
4115
4116
4117
4118
4119
4120
4121
4122
4123
4124
4125
4126
4127
4128
4129
4130
4131
4132
4133
4134
4135
4136
4137
4138
4139
4140
4141
4142
4143
4144
4145
4146
4147
4148
4149
4150
4151
4152
4153
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
4164
4165
4166
4167
4168
4169
4170
4171
4172
4173
4174
4175
4176
4177
4178
4179
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221

In [27]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special guest randi j',
 'hillari clinton make bipartisan appeal staten island',
 'new senat major leader main goal gop scari',
 'inferno overpopul myth',
 'anti trump forc seek last ditch deleg revolt',
 'sander trounc clinton w va make differ',
 'donald trump chang campaign slogan prove racist',
 'pure chao donald trump campaign manag offer glimps govern style spoiler alert terribl',
 'syrian war report novemb syrian militari deploy advanc battl tank aleppo',
 'gop insid carli crush',
 'jeffrey sewel et al metabiolog face face artifici intellig video',
 'necessari relax stretch',
 'brexit encourag uk trade non eu state includ russia',
 'interview socrat anoth day life empir near endgam fool ever hope chang',
 'mike penc drape shawl immodest ladi justic statu onion america finest news sourc',
 'first ever hindu woman elect congress',
 'donald grope hillari trump weiner sext',
 'ex assist fbi director clinton crime famili',
 'hillari want aggress interventionist foreign polici',
 'parti want craft populist messag',
 'first take wall street bid goodby june hike',
 'real disclosur secret alien base found moon tycho crater',
 'homeless woman protect trump walk fame star violent leftist',
 'tweet storm saturday clinton continu mock trump friday meltdown',
 'signific pipelin spill alreadi year expos troubl safeti record',
 'obama make right call tough afghanistan',
 'senat race rank dem attack gop lay swing state groundwork',
 'know boy want rape court throw muslim migrant child sex charg german shock',
 'pieczenik rogu fbi agent wikileak spearhead movement stop clinton steal white hous truthfe',
 'american polit reach peak polar',
 'anti muhammad cartoon contest free speech deliber provoc video',
 'effect substanc abus individu famili commun',
 'tree shape vertic farm grow acr urban crop',
 'new comment featur ad',
 'world newspap react hebdo attack',
 'ying yang gold silver set',
 'close primari warp democraci',
 'polic turn badg rather incit violenc stand rock protestor',
 'donald trump hillari clinton caus tremend death',
 'detroit women halloween decor depict real life horror shoot polic polic',
 'biden make anoth surpris polit stop',
 'hillari clinton declin favor number context',
 'comment quid pro quo wikileak email reveal clinton campaign eye paul ryan rel suprem court lenor lee',
 'hillari clinton crimin investig keep move forward',
 'rubio part shot trump',
 'loretta lynch becom first african american woman ag',
 'funni republican upset facebook column',
 'fbi check orlando shooter wife knew attack plan warn polic',
 'googl youtub hillari purs',
 'handicap hispan vote goper',
 'truth radio laconia incid',
 'gop establish nightmar ted cruz vs donald trump',
 'berni sander lost poor voter south carolina big margin problem polit revolut',
 'get botox',
 'jeb bush pick endors lindsey graham',
 'republican race enter new volatil phase',
 'hand shoot built lie',
 'lavrov kerri discuss syrian settlement',
 'break doj say help review k email truthfe',
 'berni sander call ouster two convent co chair reject',
 'five reason new york democrat primari felt competit',
 'get around congress obama turn citi hall',
 'celebr deathmatch darkmoon sage make final predict us elect',
 'john kerri isi respons genocid',
 'mitt romney invent anti poverti warrior',
 'king fill suprem court vacanc',
 'ted cruz toast presid day senat number',
 'obama speech selma answer question love america',
 'berni sander go',
 'exclus gop campaign plot revolt rnc',
 'revel unleash unlock mysteri bibl mysteri book',
 'silent counter coup intel agenc stop crook clinton video',
 'hillari clinton berni sander town hall',
 'french polic hunt two brother accus charli hebdo terror attack',
 'mandela effect made one overlook year old man ascend master video proof',
 'cnn one voter make differ vote repeatedli',
 'give social secur recipi ceo style rais',
 'firework erupt trump bush rubio cruz gop debat',
 'obama sound like critic admit complet strategi iraq',
 'ted cruz becam ted cruz',
 'newli approv gm potato potenti silenc human gene',
 'accord reach sander sue dnc suspend access critic voter list',
 'latest patriot act reform enough rein nsa',
 'fbi expand probe clinton email launch independ classif review',
 'gari johnson',
 'arcturian group marilyn raffael octob video',
 'nuclear weapon question',
 'kevin macdonald celebr trump amaz victori',
 'amaz aqutru water filter version stock snag unit natur news reader deep discount',
 'happen clinton drop',
 'brother id suicid bomber belgium',
 'glorifi violenc',
 'russia may run patienc respond usa rude',
 'david duke show hillari treason trump duke win',
 'blame immigr san francisco shoot',
 'netanyahu allow israel submerg refuge',
 'apocalyps trump voter warn revolut clinton win',
 'geo engin unlik work conserv group say',
 'question ahead tonight democrat debat',
 'obama terror strategi fail us must heed lesson',
 'berni need ground pulp leak email john podesta februari',
 'selma year john lewi recal march',
 'long overdu presidenti assassin anyway',
 'flip flop vox warn seriou risk elect day violenc good kind either',
 'third parti presidenti candid fight poll spot debat',
 'bush rubio kasich eye one anoth shadow trump',
 'comey must explain advis obama publicli accus russia hack democrat',
 'putin congratul trump say russia readi restor relat us',
 'monsieur malbrough est mort new eastern outlook',
 'conspiraci theori swirl around death antonin scalia',
 'one elect thread ehhh',
 'mccain trump understand syria',
 'trump manag say undercov voter deliv win us elect',
 'wikileak bill clinton differ bill cosbi podestaemail',
 'report megyn trash trump newt murdoch announc replac avail',
 'suspect captur ambush style kill two iowa cop',
 'thing everi american know donald trump plan save u economi',
 'next presid big impact climat polici even without congress',
 'look shock number kid born illeg',
 'mother daughter remind msnbc report trump black support',
 'justic depart staffer monitor poll elect day',
 'elizabeth warren blast fbi director go hillari instead wall street crook',
 'poll percent dem think clinton keep run even indict',
 'trump',
 'iran deal unravel think institut',
 'saturn baffl hexagon rage storm four time size earth chang color',
 'cyru mistri renam rohit sharma mistri get job back',
 'fbi interven elect',
 'donald trump win year month day old first full day offic',
 'shutdown clash return forc decemb',
 'classless obama refus photo op white hous welcom trump',
 'comment maryland trump support switch vote hillari misterdawg',
 'stuff news one talk elect',
 'blizzard charg countercharg melt away opinion trump clinton frozen',
 'social media censor fbi open clinton email investig',
 'obama inch closer veto proof support iran nuclear deal',
 'clinton plan stop sander momentum',
 'martin malley prais senat democrat hold trade deal',
 'shi ite militia join iraq mosul attack',
 'super pac get earli start push clinton campaign',
 'christian attack us must promot religi freedom',
 'u taxpay pay million dollar year privileg spi',
 'video journalist shot militar polic stand rock conduct interview',
 'buffett ran fed would rais rate significantli',
 'tension russia even real',
 'iran agre nuclear restrict framework deal world power',
 'comment constip bodi constip bodi thehealtholog',
 'fifteen quot prove fals flag terror exist shadow govern',
 'berni sander vast univers donor map',
 'former ambassador andrew young call end water fluorid civil right issu',
 'trump new ad portray everi mother worst nightmar noth short chill',
 'undercov video expos obama plan make american gun law like britain truthfe',
 'happen obama forget gop run congress',
 'syrian war report novemb isi al nusra attempt cut govt suppli line aleppo',
 'christian celebr halloween',
 'sunday charleston worship emanuel ame',
 'make matter wors syria',
 'fact check hillari clinton speech democrat convent annot',
 'bust clinton foundat directli tie plot steal elect',
 'connecticut becom first state boycott indiana lgbt discrimin law',
 'scott walker confront doubt grasp foreign polici',
 'iran carri new ballist missil test',
 'assang donald trump allow win clinton isi fund interest',
 'joe biden get respect',
 'come paul ryan must run right right',
 'berni sander need start win big state big',
 'leak obama trade deal',
 'michael moor admit women ever melt ice cap bomb american histori',
 'someon tell truth freddi gray death',
 'prison employe plead guilti aid escap two murder',
 'culchi tri explain rule one time',
 'elect day legal pot ohio democrat lose south',
 'presid trump coloss failur democraci terrifi new realiti',
 'go',
 'raqqa mosul politician fiddl middl east burn',
 'chri christi lose home state donor jeb bush make inroad',
 'washington home depot store receiv order five thousand gallon gold exterior paint',
 'western lynch mob russia tie absurd anot inform',
 'sander ralli support around clinton dnc email leak',
 'histor climat deal sight nation pars final text',
 'live time individu immens power',
 'trump slam corrupt media women make sexual assault claim',
 'dement imbecil want killari reign terror',
 'anti trump advert side bu realli visual clever see motion',
 'american disconnect realiti insouci becom euphem',
 'unspoken rule cover hillari clinton',
 'hillari melt weiner public pic prove campaign implod',
 'clinton vs trump latest elector predict greg laden blog scienc technolog',
 'jubile year merci end novemb follow judgment',
 'iraq launch oper isi anbar provinc',
 'ukip mep steven woolf mike hookem report french polic strasbourg scuffl',
 'justic kennedi scalia divid gay right',
 'justic clarenc thoma describ washington dc broken',
 'week pictur week octob onion america finest news sourc',
 'jeb bush foreign polici plan militari spend encourag peac',
 'john kasich conserv least sane',
 'audio emerg hillari clinton propos rig palestin elect',
 'author search clue raid thwart potenti belgian charli hebdo attack',
 'classic footbal banner time',
 'tweetwav',
 'trump gettysburg address new world order',
 'debat goal democrat candid',
 'spin speak email show pentagon readi roll benghazi attack occur',
 'case studi obamacar lawsuit base mythic histori',
 'trump proudli declar peopl insult deserv',
 'dem sue gop trump rig complaint',
 'us airstrik iraqi armi slow advanc mosul',
 'iran letter blowback startl gop',
 'clinton camp desper russia train wwiii',
 'donald trump gop civil war',
 'comment taint measl vaccin kill children syria tragic death use promot vaccin fear fenc vaccin',
 'laura bush hint rather see hillari presid',
 'scott walker rick perri show limit super pac',
 'catcal polit correct',
 'hillari unleash wwiii inform',
 'time reconsid lifetim appoint suprem court',
 'clinton deleg win dem nomin ap report sander question talli',
 'hillari implod trump took everyth paid noth support us',
 'trump say obama born us period new birther dust',
 'mh debri part miss plane next',
 'googl plan massiv ai integr social network spi tool hillari campaign',
 'israel stole classifi us inform use help congression republican',
 'america simpl ideolog one russia top us expert explain america',
 'poll show trump made point week like poll',
 'chao hous floor dem republican clash lgbt propos',
 'new studi link fluorid consumpt hypothyroid weight gain wors',
 'clinton sander accus trump incit violenc',
 'memo next administr defens spend must actual defens',
 'new respons hillari clinton insist email setup matter conveni',
 'trump mull altern option make mexico financ wall',
 'circu liar america three ring evil clown',
 'donald trump said univers educ actual goal sell sell sell',
 'trump forev chang american polit',
 'kerri advis mari harf twitter fight iran nuke',
 'role us nato eu relat china manlio dinucci',
 'daili mani african american unenthusiast settl hillari clinton',
 'peopl come recent berni sander ralli',
 'trump presid mean world countercurr org',
 'fleec congress grill kerri obama offici iran nuke deal',
 'page hack wikileak email teach us hillari clinton',
 'comment break cdc block testimoni senior scientist blew whistl sever medic malpractic cdc accus block testimoni senior scientist new york malpractic injuri lawyer blog',
 'fox news admit made stori hillari indict foundat',
 'repudi media',
 'buchanan smash cnn shill',
 'imposs happen cub win world seri ye hillari clinton like indict',
 'america elect gullibl shatter david keran',
 'anderson cooper absolut own kellyann conway fbi clear hillari video',
 'schlong nyt fbi reopen hillari probe thank anthoni weiner',
 'american realli think elect coverag',
 'exclus sieg islamabad',
 'fix nbc affili accident post elect result week earli hillari win presid trump',
 'lynch school wingnut right tri fail wound obama ag nomine',
 'ye ted cruz could win',
 'build wall hand small nyc anti trump protest stream live',
 'trump advisor tri pivot fishtail',
 'christian drop none soar new religion portrait',
 'comment brother clinton campaign chair activ foreign agent saudi arabian payrol marlen',
 'insid deliber hillari clinton campaign launch',
 'american express disown pink floyd singer roger water pro palestinian view',
 'clinton condemn trump chicago violenc',
 'franc grow debat speech protect',
 'presid elect donald trump first televis interview sinc elect inform',
 'north carolina hillari support brag facebook vote multipl time',
 'russia react un aid chief aleppo kill zone remark',
 'repres govern thugocraci',
 'gay right religi liberti american',
 'rand paul stall ted cruz seek pick support among libertarian',
 'dream come true hillari clinton wall street journal editori board rip ted cruz',
 'obama press putin strike ukrain peac deal',
 'trumka disappoint obama warn hillari',
 'pro palestinian propaganda lower standard truth america',
 'wingnut death grip congress paul ryan control hous gop',
 'lift weight could ward dementia make smarter',
 'peopl excit christma advert told rest human cultur',
 'state depart warn possibl terror attack south africa',
 'lost iraq',
 'pope franci implor congress accept immigr',
 'poll trump gain iowa still domin new hampshir',
 'rand paul goe senat floor protest nsa spi measur',
 'china airport secur robot give electroshock',
 'obama detail disappoint netanyahu first post elect comment',
 'wikileak neera tanden anoth ring endors hillari realli',
 'realiti check first clinton v trump presidenti debat',
 'doomsday elect',
 'john kasich advic women prevent sexual assault avoid parti lot alcohol',
 'system set boehner failur',
 'gay marriag victori suprem court trigger backlash',
 'rode best jess jackson mount fight pipelin leonardo dicaprio rescu',
 'mccarthi drop speaker race hous ask want job video',
 'democrat republican tight race iowan prepar caucu',
 'iran best outcom keep negoti without reach deal',
 'nazi fli saucer perman base antarctica',
 'break man brag facebook vote time reveal',
 'furiou parent slam damag bbc sex chang show aim six year old',
 'trump famili say trump brand damag',
 'rand paul flatlin',
 'nurs chri christi quarantin ebola goe governor vaccin',
 'paul ryan donald trump coexist within republican parti',
 'cruz copi border wall trump say',
 'john oliv america increasingli segreg school rare equal way video',
 'rise mandatori vaccin mean end medic freedom',
 'scientist fascin lake sea enter never come watch',
 'jeb bush lose tv ad edg marco rubio',
 'russia india discuss fgfa advanc fighter su mki upgrad',
 'real polic race problem divers forc white resent america persist divid',
 'suprem court cannot hide obamacar',
 'break ted cruz call special prosecutor investig hillari truthfe',
 'poll hillari clinton berni sander top trump',
 'donald trump revok washington post press access video',
 'real reason obamacar come unglu',
 'jeb bush avoid jon huntsman',
 'reviv clinton email scandal kill slew new fact record time',
 'iraq sky darken islam state torch oil',
 'new yorker fight overturn ballot selfi ban',
 'poll find ben carson knock donald trump top spot nation',
 'glad surpris palestinian reaction netanyahu win',
 'georg w bush ethic lawyer file complaint fbi director jame comey',
 'netflix ceo tv futur includ hallucin pill',
 'ernst trump stop name call',
 'comment elect beammeupscotti',
 'debat duke say usa becom banana republ',
 'five fbi field offic probe clinton chariti ad fuel fire',
 'white hous gop fail put point board',
 'daili presid hillari clinton lose way could lose',
 'democrat want berni want berni',
 'podesta wiki leak prefer muslim christian',
 'critic pounc madelein albright exhort women back clinton',
 'clinton doubl disput claim fbi found email remark truth',
 'clinton haiti develop plan succeed disappoint',
 'cours facebook bias real problem admit',
 'tax calcul feder debt',
 'trump advis remain split far move toward middl',
 'clinton final stretch win anti trump conting may best play',
 'australian taxpay charg million donat corrupt clinton foundat',
 'vatican end scrutini u nun',
 'clinton email scandal took root',
 'jew blame holocaust hous lord event',
 'disappear middl elector way less moder past primari',
 'hanniti wikileak proven everyth conspiraci theorist said true',
 'russia success test first ever hyperson weapon',
 'hulk actor mark ruffalo join stand rock protest dapl',
 'ap fact check republican debat fact',
 'drop incom inequ',
 'walmart goe grain obama america new thanksgiv ad',
 'senat make histori confirm loretta lynch u attorney gener',
 'manhunt escap killer expand vermont',
 'path total dictatorship america shadow govern silent coup',
 'youth day elect anoth world possibl',
 'physic gold demand fear',
 'protest charg shoot offic ferguson',
 'comment u war iran alreadi begun',
 'locker room talk lock talk',
 'gop brace trump loss roil refus accept elect result',
 'one old vh tape may worth',
 'obama trump unfit serv presid',
 'pope franci met kim davi matter fight religi freedom video',
 'studi phytochem found broccoli cauliflow attack prostat cancer cell',
 'david duke win louisiana senat debat landslid despit blm riot',
 'pari tragedi could shake race',
 'hillari clinton radioact sot',
 'first gop debat six thing look charleston',
 'black hawk crash florida human remain found',
 'video creepi clown get pistol whip',
 'vision thing inform',
 'drudg koch soro bezo non politician determin next presid',
 'way know',
 'obama putin outlin compet vision syria',
 'comment polic offic wife caught fake robberi scheme frame black live matter cat vagina nasti woman',
 'gop lose walmart',
 'suprem court decid weigh transgend right',
 'hillari clinton charg obstruct justic could go prison year',
 'top secret email clinton server discuss drone program may refer classifi info',
 'miracl man metaxa vs close mind close univers',
 'obamacar premium spike averag',
 'collect conscious individu gone',
 'obama gun control emot evolut',
 'scientist found insid year old pot chang histori',

In [28]:
corpus[1]

'watch exact moment paul ryan commit polit suicid trump ralli video'

In [29]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3117, 2108, 2020],
 [3402, 1145, 674, 625, 186, 208, 4753, 2621, 3245, 4418, 4823],
 [1335, 1105, 1197, 4661, 3997],
 [1432, 4013, 3044, 2210, 4252, 418, 4059, 3430],
 [4067, 39, 1905, 1429, 1075],
 [1057, 1354],
 [958, 107, 3402, 1343, 4447, 1482],
 [4335, 1885, 4814],
 [1183, 2145, 3245, 718, 2488, 321, 4496],
 [2668, 1779, 1189, 39, 1299, 3408, 3425, 1281, 2724],
 [2581, 718, 443, 635, 3531, 16, 2108, 718, 2424],
 [490, 3245, 4460, 4116, 961, 2414, 2918, 3055, 3012, 146],
 [3653, 468, 3010, 2176, 2915, 2193, 531, 3673, 4823],
 [1358, 1246, 394, 4697, 1630],
 [3245, 4551, 110, 2537],
 [170, 164, 4058],
 [4607, 1425, 2375, 2108, 2166, 1963, 4264, 2238, 850],
 [2108, 718, 4898, 4305, 1246, 4051, 472, 3437, 2069, 715, 1776, 34, 531],
 [2668, 4350, 2375, 2561],
 [2341, 2603, 189, 277, 241, 128, 1246],
 [3081, 110, 3245, 1215, 1396, 3951],
 [4048, 2175, 3747, 3552, 3306, 50, 4787, 377, 2653],
 [2108, 718, 1189, 1856, 850, 2175, 1699],
 [39, 3458, 2691, 4723, 1341, 2580, 2631, 1829],
 [4241, 3943, 3966],
 [2044, 3245, 754, 3935, 152, 1536, 961, 3880],
 [1343, 525, 718, 1642, 2543, 1189, 4058],
 [490, 3245, 2354, 2424, 272, 2095, 1845],
 [4962, 4484, 490, 3245, 2424, 1748, 707, 635, 754, 2034, 35, 1161, 2356],
 [4254, 1630, 3738, 939, 4254, 4740, 4308, 2617, 4067, 875, 4018],
 [2631, 2603, 1943, 1303],
 [2014, 247, 4481, 3001, 3563, 1788, 1788, 346, 3679, 4823],
 [1483, 4059, 1437],
 [4991, 3480, 2240, 2199, 2907, 91, 1691, 1883, 4419],
 [2469, 3814, 1654, 2338, 1881, 4573, 731, 4696, 213, 4037, 2860, 2354],
 [2596, 3240, 4226, 3448, 4825, 210, 3497, 675, 4638, 1246, 4274, 531, 62],
 [3468, 4037, 2641, 2348, 505, 889],
 [490, 707, 2108, 3245, 40, 4517],
 [610, 4332, 2579, 297, 718, 820, 4560],
 [2108, 4039, 153, 3072, 164, 1934],
 [2500, 4039, 1871, 1838, 3823],
 [3468, 4551, 1182, 3717, 2477, 1735, 2468, 2078],
 [2308, 131, 718, 1388, 96, 4421, 1766, 4314, 196],
 [4884, 2348, 675, 3245, 1210, 3192, 219, 1465, 2968],
 [49, 3010, 2188, 718, 832, 3659, 3245, 456, 2506],
 [2153, 3685, 4664, 4751, 3968, 613, 4305, 4172, 1301],
 [2375, 1189, 170, 2063, 855, 1218],
 [3458, 3028, 2070, 1047, 4987, 2631, 109, 2288, 1691, 4320],
 [241, 3350, 4039, 2238, 1088, 494, 3951, 4392, 3055, 2309, 1049, 3352, 4607],
 [1233, 1156, 2579, 1904, 4987, 3079, 214, 1131, 718, 2321, 4245, 4707, 2325],
 [1848, 4753, 2999, 766, 4118],
 [2044, 2929, 2151, 622, 200, 1651, 4977, 2669, 4823],
 [3471, 785, 1620, 1270, 4560, 3495],
 [414, 1588, 1805, 4939, 2779, 3261, 3305, 2037],
 [39, 15, 50, 1183],
 [4697, 652, 3444, 3874, 4987],
 [3292, 221, 4326, 1009, 4546],
 [4090, 1429, 2749, 1794],
 [743, 2581, 1146, 197, 1825, 2585, 4213, 3730, 1961],
 [490, 3245, 2108, 718, 2844, 709, 3667],
 [159, 170, 4184, 4373, 2001, 2308, 1881, 1320, 1302, 743, 743],
 [3764, 1189, 1654, 4005, 4753, 1131],
 [2108, 718, 1467, 293, 2695, 469],
 [15,
  2642,
  1347,
  4327,
  4987,
  510,
  3380,
  718,
  2424,
  382,
  625,
  186,
  106,
  4186,
  1088,
  555,
  1326],
 [2108, 718, 3151, 4865, 1409, 1754, 466],
 [3966, 1482, 699, 3245],
 [2699, 4581, 4349, 3468, 3931, 1848, 2348, 2410],
 [4252, 2164, 4881, 1667, 3439],
 [2579, 2145, 873, 3003, 1449, 3977, 4987, 73, 3430, 743],
 [4632, 3416, 2108, 4609],
 [4377, 3864, 1316, 3448],
 [4565, 1744, 3879, 4291],
 [2631, 3227, 3107, 654, 110, 2557, 490, 3245],
 [1432, 1343, 2974, 3225, 3808, 2281, 2100, 2755, 1640, 422, 4753, 1774],
 [4603, 4167],
 [3181, 549, 423, 3944, 489, 4771],
 [2164, 3028, 2301, 39, 260, 2711],
 [1485, 1302, 1759, 1295],
 [2547, 1335, 3278, 4254, 2691],
 [871, 4893, 4702, 71, 668, 1333, 510, 2325],
 [1432, 1343, 2063, 4284, 15, 1188, 4941, 1663, 3036],
 [3675, 2992, 39, 1905, 1364, 1429, 4719, 3184],
 [4603, 2944, 889, 2375, 2581, 1944, 3625],
 [4290, 4091, 2271, 4731, 1189, 3498, 1878, 4508, 505],
 [816, 1335, 2344, 470, 4768],
 [2872, 2731, 4630, 2044, 1140, 2838],
 [3487, 4241, 4186, 1088, 4900],
 [654, 110, 4989, 1708, 2338, 3458, 2695],
 [2375, 1651, 1696, 3191, 4356, 257, 1246],
 [1432, 1343, 1105],
 [2197, 2631, 2424, 1589, 3880, 3330],
 [1412, 1358, 3938, 2136, 3211, 2136, 508],
 [319, 4662, 1110, 3737, 4644, 1131, 3726, 718, 4823],
 [2108, 718, 1432, 1343, 104, 3625],
 [152, 743, 1609, 15, 4902, 411, 251, 3874, 1084, 4987],
 [337, 3471, 4693, 207, 691, 3968, 621, 4697, 1807, 1095, 4823, 531],
 [2840, 207, 3808, 1189, 4058, 1316, 2660],
 [1094, 4122, 2348, 4369, 2880, 2034, 4589],
 [3906, 2210, 3245, 549, 3966, 110, 2631, 1855],
 [2375, 1455, 2561, 555, 3331, 3958, 3882, 332],
 [654, 110, 3692, 654, 110],
 [2377, 2038, 4672, 3829, 4753, 1911, 3045, 3142],
 [4408, 2999, 1343, 4024, 418, 1780, 1704, 555, 3808, 571],
 [1999, 2729, 301, 112, 2459, 3464, 196],
 [2579, 4120, 1390, 718, 510, 574, 2845, 295, 668],
 [3856, 3234],
 [3882, 1557, 1887, 4079, 1085, 4823],
 [1281, 3356, 4356],
 [2183, 3107, 4290, 3245, 223, 4345],
 [223, 3776, 2770, 4637, 968, 2927, 3467, 710, 4765, 531, 895, 1237, 3024],
 [3161, 718, 1131],
 [4902, 1581, 2621, 1577, 3982],
 [4153, 2585],
 [4419, 2840, 466, 1601, 4836, 1354, 2793],
 [3946, 2268, 3823, 2108, 2077, 3245, 2268, 4180],
 [694, 3086, 105, 970, 1302],
 [4374, 4727, 4968, 411, 4758],
 [622, 3245, 3808, 3430, 1774, 718, 4180],
 [1611, 1467, 4487, 3991, 2485, 1557, 4702],
 [4356, 2184, 3225, 1364, 1855],
 [2375, 1084, 3882, 930, 4508, 4182, 3760, 3254],
 [1432, 277, 4741, 970, 861, 510, 816, 798, 700],
 [1696, 3968, 816, 2373, 4496, 2352],
 [2719, 3909, 1661, 2922, 3742],
 [648, 198, 283, 3430, 2510, 2915, 505, 2338, 2585, 4428, 4310, 3136],
 [101, 2500, 1661, 1670, 4559, 3801, 1503, 1855],
 [549, 3966, 2133, 382, 207, 1654, 174, 3245],
 [758, 4182, 2603, 497, 2375, 3586, 411, 4419, 3616, 1364],
 [2775, 519, 3245, 4702, 4419, 4014, 2812, 2074, 4508],
 [1579, 1302, 4324, 4944, 39, 3110, 765],
 [3960, 1875, 4730, 2944, 3667, 2822, 2109],
 [207, 505, 2391, 4003],
 [3642, 3245, 4841, 3423],
 [3245, 1748, 4702, 1096, 3808, 2364, 4180, 4508, 505],
 [4987, 4350, 718, 4058, 4350, 435, 2981],
 [3738, 247, 3176, 3245, 1544, 4180, 3627, 4850, 2142],
 [3190, 153, 4581, 2034, 4135, 15, 443, 2451],
 [3437, 3742, 1848, 241, 490, 3245, 73, 12, 3911, 4628],
 [1021, 1708, 2755, 138, 2373, 1934, 3012, 3379, 889],
 [533, 4607, 2695, 2403, 4298, 509],
 [1204, 2969, 3884, 1592, 3738, 3245, 2850, 4013],
 [3497, 108, 1603, 3382, 3801, 505, 2338],
 [1384, 3401, 884, 2579, 297, 1105, 2108, 3447, 1182, 3717, 3726],
 [3801, 2189, 1047, 4575, 718, 1409, 466, 3012, 3022],
 [3245],
 [2668, 116, 1489, 4575, 3507],
 [524, 2712, 8, 666, 3010, 3166, 745, 1585, 4321, 2354, 1284],
 [3306, 2402, 973, 3948, 2605, 2402, 4603, 329, 3317],
 [2579, 1721, 505],
 [490, 3245, 4180, 3968, 4034, 2338, 621, 3468, 1943, 2338, 4808],
 [1213, 4935, 487, 754, 3455],
 [2854, 2375, 1754, 3424, 4118, 4245, 4707, 4727, 3245],
 [15, 3499, 3245, 4013, 2227, 1316, 2108, 518],
 [3648, 531, 207, 2724, 505],
 [2479, 1049, 2988, 493, 229, 525, 3245, 718, 2364],
 [4122, 2707, 4253, 2579, 2175, 718, 510, 4865],
 [2375, 2275, 2590, 3234, 531, 4013, 2668, 1281, 116],
 [718, 73, 1131, 1343, 2466],
 [3607, 518, 3909, 3458, 1364, 2944, 2199, 116],
 [50, 2812, 4904, 1197, 332, 3647, 4987],
 [2648, 153, 4603, 2018, 4912, 1299, 718, 2424],
 [2822, 4987, 4508, 4182, 850, 1026, 3532],
 [3911, 4082, 1393, 3325, 3039, 3968, 2792, 3976],
 [4823, 1780, 699, 710, 743, 4213, 3730, 3531, 2469],
 [4978, 700, 2762, 1790, 4589, 3259, 1301],
 [1142, 4419, 3012, 2308],
 [2668, 4397, 1281, 4737, 917, 116, 4697, 3427],
 [15, 1473, 566, 1473, 566, 373],
 [4361, 4078, 2095, 3907, 1677, 1084, 1251, 174, 754],
 [1432, 1343, 3152, 1728, 437, 3111],
 [2063, 1694, 2468, 2881, 2063, 4507, 2770, 1786, 4165, 170, 2274],
 [3245, 39, 1183, 2519, 3742, 1204, 1409, 3107, 4843, 2672, 1782],
 [1096, 4823, 613, 2375, 73, 1189, 1848, 2460, 2539, 2561, 4335, 2325],
 [3161, 2375, 4457, 2631, 466, 889],
 [4254, 1630, 3738, 939, 2344, 3001, 572, 300, 1457, 4303, 2696, 580, 4018],
 [2822, 4290, 4184],
 [2175, 188, 4746, 464, 3368],
 [1189, 1075, 146, 3423],
 [1183, 2145, 2108, 718, 1651, 1364, 1188, 1252],
 [4108, 718, 4934, 381, 4624, 1589, 2321, 505],
 [4604, 4349, 3468, 1691, 2264, 4014, 414, 3693, 2539],
 [3178, 985, 226, 220, 3252, 164, 1934],
 [2668, 4904, 39, 4624, 1126, 4648],
 [983, 490, 3245, 4727, 4180, 718, 2344, 1717, 3097],
 [3670, 3764, 4603, 2111],
 [1336, 625, 186, 4182, 466, 170, 170],
 [1432, 1343, 277, 4912, 4180, 2755, 1691, 2755],
 [861, 2375, 2199, 116],
 [1334, 4063, 3331, 170, 4037, 493, 2515, 1232, 3195, 1848, 1859],
 [1329, 291, 4565, 4552, 278, 3667],
 [1700, 3483, 4909, 849, 1980, 1825, 15, 1387],
 [2927, 4059, 2603, 796, 207, 745],
 [505, 2338, 1706, 2220, 1195, 1364, 122, 2281],
 [1708, 3245, 1884, 3743, 1794, 4648, 39, 1048],
 [1105],
 [3677, 3647, 2993, 3942, 32, 624, 1919],
 [1702, 2157, 122, 2990, 1691, 437, 3181, 549, 1189, 434],
 [3002, 2990, 1429, 3094, 1426, 3622, 3675, 4715, 4494, 4326, 3413, 1454],
 [4213, 4581, 1232, 4419, 4624, 2505, 536, 1724],
 [1343, 4418, 4013, 2944, 718, 418, 510, 861],
 [688, 2373, 116, 1295, 1825, 2330, 3498, 1943],
 [4458, 745, 1270, 2958, 3427],
 [3245, 296, 3325, 2707, 170, 1189, 2065, 4937, 2429],
 [359, 4477, 4039, 1262, 408, 1084],
 [2044, 3245, 1161, 3819, 3348, 1606, 3258, 4543, 1951, 3378],
 [1848, 729, 1048, 618, 4349, 2747],
 [2859, 796, 3269, 2108, 718],
 [2108, 493, 40, 955, 614, 2095, 2424, 2998],
 [718, 2557, 3245, 1999, 2543, 1878, 3572, 3838, 1497, 3975, 4239],
 [1034, 3968, 4343, 4507, 939, 2289, 1556],
 [332, 574, 2108, 2344, 3925, 4708],
 [4512, 4433, 3819, 158, 2596, 2157, 3738, 152, 743, 4011, 3065],
 [3497, 2223, 2109, 2982, 2339, 170],
 [3497, 4841, 3592, 2316, 3002, 2149, 3475],
 [1599, 715, 1599, 1085, 4638, 1246, 4274, 531, 62],
 [3181, 549, 164, 1934, 73, 4740, 3454, 3480, 4170],
 [816, 2133, 2485, 737, 486],
 [2100, 380, 2108, 718, 1215, 3635, 3014, 505],
 [501, 611, 3196, 1962, 2714, 4753, 4924, 251, 3874, 4987],
 [4466, 3839, 4918, 745],
 [204],
 [3245, 3936, 712, 39, 4697, 3622],
 [1855, 2580, 1364, 1670],
 [2910, 3063, 510, 3823, 1864, 4014, 3691, 60, 4987, 324],
 [2090, 2637, 4095, 2957, 96, 2047, 1859],
 [3245, 3860, 2918, 1024, 4328, 4551],
 [1047, 4024, 2631, 3245, 3635, 771],
 [4508, 451, 1754, 1110, 2644, 2617, 3647],
 [2668, 3120, 4292, 4421, 2631],
 [718, 2522, 981, 4419, 529, 3268],
 [490, 3245, 2631, 4165, 1630],
 [15,
  533,
  2607,
  1663,
  4135,
  2129,
  3423,
  641,
  3667,
  4262,
  850,
  1663,
  2020,
  4859,
  1663],
 [4118, 549, 1148, 197, 1951, 2108, 1708],
 [3178, 985, 1236, 4840, 3823, 4304, 2648, 153],
 [2058, 4753, 2332],
 [2108, 1358, 3268, 1724],
 [745, 3963, 1056, 841, 4186, 1088],
 [718, 961, 4180, 1047, 2958, 3062, 3738, 1343, 4356, 2414],
 [2108, 2998, 3245, 3450, 189, 1691, 4843, 4013, 4508],
 [3245, 4702, 2375, 4298, 4508, 4357, 39, 4060, 2165],
 [1090, 394, 1482, 1577, 811, 1021],
 [4632, 73, 2998, 4474, 3501, 4122, 1190, 3976, 213, 2108, 2424],
 [4968, 3813, 1014, 4508, 1724, 4262, 71, 4162, 2164],
 [1246, 3020, 4844, 207, 4419, 4380, 4508, 243, 2603, 1246],
 [3801, 3823, 3245, 4693, 3758, 1599, 2561, 3801],
 [4484, 4707, 3987, 1047, 2164, 4935, 414, 1215],
 [39, 2637, 2090, 1786, 1135, 933, 3709, 3246, 146],
 [718, 1343, 411, 3245, 1825, 2585],
 [2702, 1021, 1737, 2861, 3454, 4182, 4028, 2861],
 [39, 470, 2108, 718, 3219, 510, 4657, 1075, 4531],
 [3245, 3304, 2415, 3509, 1189, 3545, 3198, 1182],
 [3421, 3276, 1246, 2581, 2455, 498, 1710],
 [490, 3245, 2083, 1728, 3254, 4028, 2580, 3299, 3299, 3299],
 [3245, 3577, 2354, 1848, 4753],
 [1335, 497, 4690, 1809, 3044, 4559, 2668, 4500],
 [289, 4508, 2357, 91, 2074, 4147, 4659, 671],
 [317, 1339, 3931, 1848, 2656, 4160, 2108, 718],
 [1024, 1336, 3239, 1432, 1343, 4418],
 [3245, 1708, 3238, 4697, 2791, 1479],
 [691, 889, 3922, 1335, 2375, 1036, 2668, 4500, 116],
 [415, 3616, 4987, 510, 3192, 4508, 2108, 718],
 [15,
  871,
  4446,
  3211,
  4880,
  2833,
  4765,
  2642,
  3391,
  3452,
  2439,
  308,
  4446,
  411,
  3211,
  4880,
  2833,
  4765,
  39,
  1905,
  308,
  627,
  3291,
  1497],
 [2751, 531, 3331, 4693, 4006, 2108, 3022, 4934],
 [2411, 2707],
 [1143, 4246, 2840, 646],
 [2094, 3161, 4221, 4180, 4697, 980, 3704, 2108, 718, 2561, 3022],
 [1246, 505, 2960, 2465, 3946, 1930],
 [3745, 2504, 3210, 3058, 3588, 2139, 2579, 1308, 2108, 4823],
 [3142, 342, 2579, 1793, 2108, 1390, 4212, 2348, 40],
 [1848, 1606, 4575, 505, 1186],
 [2197, 1531, 4337],
 [4339, 4867, 1165, 1188, 1001, 505, 93, 1599, 2018, 2108, 4180, 1708, 3245],
 [4581, 4568, 4149, 170, 4059, 930, 2871, 2375, 2410, 806],
 [3704, 654, 110, 1444, 4180],
 [233, 1182, 1485, 581, 2146, 2044, 3245, 3039, 2386, 4458],
 [3245, 1725, 4059, 393, 3139],
 [2822, 1131, 2433, 91, 39, 2101, 2522],
 [15, 4902, 718, 2424, 1663, 3258, 164, 1904, 139, 2389, 236, 3027],
 [2603, 4977, 2108, 718, 2424, 574],
 [1848, 2682, 4276, 1592, 2012, 1412, 3146, 2770, 1347, 4565, 3356],
 [718, 2817, 3245, 3542, 2585],
 [4713, 2779, 1855, 1651, 675],
 [1708, 505, 490, 3245, 3468, 165, 2469, 3081, 505, 1724],
 [4873, 2100, 2108, 4013, 1023, 1667, 1316, 1120, 745],
 [4419, 3444, 3312, 1980, 321, 4018, 4135, 2610, 1111],
 [1436, 754, 121],
 [2339, 170, 1026, 1776, 1848],
 [3018, 625, 2718, 654, 110, 3935, 423, 4013, 615, 1594],
 [3678, 1336, 1906, 2108, 718, 1182, 3717, 2563, 3702, 1169, 764, 654, 110],
 [2375, 2746, 2775, 4622, 1139, 4170, 116],
 [1559, 4453, 2375, 3430, 2108],
 [1347, 4565, 3275, 2204, 4782, 4565, 1246],
 [4149, 3667, 2857, 889, 625, 186, 2876, 4707, 2631],
 [2987, 3709, 1444, 1487, 3532, 1189, 48],
 [1024, 1602, 3213, 1161, 860, 2189, 3045, 3254],
 [1691, 108, 3430, 4593, 1084, 4987, 2281, 3256],
 [2974, 332],
 [4760, 368, 2490, 889, 2746, 3086],
 [3801, 3245, 3246, 443, 3658, 171, 39, 1234],
 [3018, 625, 4378, 3458, 3987, 3039, 196, 3976, 251],
 [4147, 4258, 2348, 4286, 1094, 4582],
 [2375, 3747, 4453, 4374, 3468, 1001, 505, 15],
 [4987, 3719, 2037, 1654, 2455, 3944, 2108, 1606],
 [1048, 2145, 3468, 718, 2167, 3245, 1661, 1855],
 [1758, 505],
 [816, 2133, 3683, 170, 1739, 2065, 4937, 2082, 2500, 4243, 4493],
 [554, 4546, 3883, 3743],
 [2339, 3353, 4345, 4186, 1088, 3348, 2312],
 [3523, 476, 4633, 463, 2842, 4559, 3685, 4167, 2357, 4402],
 [2590, 1131, 1680, 3028, 4707, 1012, 4039, 329, 4823],
 [1364, 2164, 2133, 3028, 4697, 394, 1142],
 [2668, 476, 292, 1409, 506, 3379, 2999, 116],
 [1880, 4847, 789, 3975, 96, 2346],
 [871, 4697, 1023, 1667, 1316, 745, 3380],
 [4609, 654, 296, 1799, 2106, 2309, 2354, 3823, 1426, 3815, 3968, 621],
 [3245, 4560, 4702, 3245, 335, 1799],
 [3018, 625, 70],
 [658, 1702, 2157, 3515, 4841, 4378, 3135, 1663],
 [625, 186, 490, 3245, 419, 4953, 2164, 2500],
 [110, 602, 4159, 1182, 3245, 4702],
 [816, 1356, 1246, 92, 3149, 4568, 1627, 3051, 1358, 4823],
 [2007, 1310, 1663, 3238, 4507, 2439, 3532],
 [4765, 2274, 158, 2896, 2301, 267, 1336, 3402],
 [3181, 549, 122, 1468, 1183, 2106, 1825, 3966],
 [4419, 465, 3278, 2079, 2617, 4247, 1578, 4016, 2032],
 [2308, 743, 3028, 422, 1568, 754, 4245, 3039, 1246, 3042, 2982],
 [4186, 1088, 4104, 4968, 4095],
 [871, 654, 110, 2063, 50, 1322, 4865, 2108, 2325],
 [3801, 2108, 718, 1432, 1343, 4380, 3245],
 [490, 3245, 2542, 3002, 1001, 2746, 1704, 4823],
 [2308, 2992, 4095, 1336, 1159],
 [3181, 549, 2082, 2951, 3491],
 [4762, 718, 510, 1061, 4135, 555, 39, 1183, 1301, 745],
 [332, 4176, 2909, 2457, 1691, 4902, 2275],
 [39, 4510, 4559, 403, 3618, 4839, 1396],
 [3801, 3616, 2300, 2932, 3877, 490, 3245, 4380, 1503, 1825],
 [3255, 4005, 4565, 160, 4374, 4180],
 [165, 1642, 549, 2214, 3291, 2222, 771, 2579, 297, 3239, 758],
 [1205, 2880, 1468, 4317, 1883, 2717, 2266],
 [1491, 3245, 1131, 3278, 2063],
 [15, 505, 1584],
 [1855, 2268, 4702, 1354, 4349, 2531, 4206],
 [3675, 2579, 3512, 4808, 1390, 718, 1665, 1183, 1205, 3531],
 [4245, 4707, 2631, 930, 408, 3758, 1169],
 [317, 1708, 2108, 718, 122, 1358, 1444, 122],
 [1364, 4039, 1432, 4039, 1432],
 [798, 507, 861, 2346, 3951, 2822],
 [555, 2504, 359, 405, 1039, 170, 3317, 718],
 [718, 404, 2350, 2429, 2579, 4421, 510, 1111, 4565],
 [718, 4550, 1421, 73, 494, 4453],
 [901, 1667, 4836, 2308, 422, 3331],
 [4399, 3259, 3540, 4159],
 [3245, 497, 2023, 3975, 1186, 1754, 1685, 32],
 [718, 3498, 1437, 4180, 2044, 3245, 799, 2840, 476, 3424],
 [4422, 4082, 1049, 3325, 2879, 3325, 718, 4934],
 [2195, 4507, 2001, 3911, 2211],
 [718, 510, 1061, 3450, 2605],
 [3476, 694, 4448, 4707, 3012, 3267],
 [94, 32, 2543, 1358, 1776, 3701, 1760, 1429],
 [4435, 4987, 4072, 189, 3960, 3610, 2083, 1906],
 [4419, 3983, 4648, 3468, 4037, 1311, 3356],
 [3545, 3034, 4255, 125, 1197, 4213, 3730, 3039, 425],
 [3062, 1183, 2145, 2164, 1855, 1183],
 [1131, 2944, 1922],
 [1152, 4378, 2666, 2375, 1246, 39, 939, 1183],
 [3458, 1189, 1859, 4396, 2699, 4581, 3911, 1252, 1222],
 [4463, 1825, 458, 4120, 2128],
 [4234, 1255, 2239, 1246, 174, 754, 319, 1110],
 [1720, 2338, 505, 1654, 4697, 4593],
 [1432, 4326, 2090, 2020],
 [3039, 1049, 1302, 4808, 2077],
 [15, 3911, 1630, 2668, 4751, 26],
 [1115, 575, 2724, 2684, 2724],
 [2631, 3602, 3245, 4972, 1566, 1754, 2746, 505, 93],
 [207, 621, 1064, 1390, 2840, 3438],
 [2375, 3245, 3627, 2920, 1708],
 [4760, 368, 3058, 4809, 1775, 1075, 4559, 1026, 3532, 4823],
 [2637, 2857, 4421, 2412, 2378, 4987, 1728, 2751, 2115],
 [3946, 2268, 4180, 4746, 3458, 1855, 3030, 4416, 1741, 3411],
 [1197, 1404, 1444, 4190, 3028],
 [2108, 718, 886, 2033],
 [3468, 2631, 1855, 3815, 3437, 533, 188],
 [2850, 3842, 339, 4467, 3045, 2023, 4421],
 [4823, 1358, 1710, 4603, 3416, 432],
 [1678, 3437, 1724],
 [4251, 3936, 4400, 757, 2907, 2993, 431, 1021, 1708],
 [1358, 241],
 [2375, 2775, 2723, 2167, 1678, 3423],
 [15,
  743,
  4808,
  1449,
  2166,
  3449,
  446,
  1250,
  201,
  2850,
  4458,
  1075,
  164,
  4766,
  393,
  2348],
 [2631, 122, 1152],
 [4186, 1088, 4167, 2122, 1237, 170],
 [2108, 718, 1049, 1070, 3497, 1444, 1105, 1700, 3968],
 [4380, 718, 510, 718, 852, 3278, 2463, 417, 2840, 4800, 1014, 3490],
 [582, 4697, 3873, 2557, 4090, 3147, 4090, 1728],
 [4095, 4650, 1741, 1715],
 [3344, 4078, 1270, 4807],
 [2375, 2460, 2876, 4193, 2962],
 [4765, 4421, 2603, 3968, 621, 2220, 2354, 1859],
 [4987, 1452, 2164, 3658, 2510, 4095, 2415],
 [3245, 3536, 1122, 39, 1234],
 [2631, 1661, 1670, 548, 4380, 718, 718, 510, 3498, 2338, 443, 1142],
 [33, 3497, 108, 2999, 743, 116],
 [3924, 4702, 4078, 3890, 1691, 1075, 2907, 1432, 2308],
 [2631, 4807, 1869, 3936, 1190, 2146, 710],
 [2203, 3304, 2436, 3245, 718, 954, 1661, 423],
 [3245, 718, 201, 4090, 1959],
 [3178, 985, 4356, 2375, 4807],
 [2108, 2343, 3813],
 [738, 3454, 413, 2977, 442, 1395, 745, 217, 803],
 [1343, 3245, 4907, 4180, 1963, 1000, 1429, 3245, 423, 1337],
 [718, 1343, 1788, 4109, 1364, 1855],
 [2386, 4565, 4213, 3928],
 [3045, 2023, 2204, 3753, 889, 2633, 811, 3623, 1036, 4702],
 [4508, 1036, 1045, 1084, 2876, 611, 1197, 4987, 3190],
 [2344, 2918, 4135, 4565, 207, 207, 956, 2023, 4279, 4968],
 [2108, 4753, 4765],
 [12, 1708, 2887, 3052, 3039, 506, 506, 4823, 3331, 1918],
 [718, 423, 3468, 2691, 3986, 3944],
 [2090],
 [2375, 3423, 1630, 4487, 4507, 1708],
 [911, 3372, 1513, 104, 4418, 2944, 743, 611, 4808, 458, 4378],
 [3458, 2617, 4350, 2038, 4347, 3685, 4416, 2375, 3234, 1769],
 [15,
  477,
  694,
  4693,
  3431,
  1197,
  477,
  694,
  4693,
  3431,
  1197,
  3344,
  4523,
  244,
  531,
  2240,
  694,
  244,
  531,
  2240],
 [4508, 3204, 3312, 1316, 2063, 4507, 3042, 1893],
 [2881, 1204, 3616, 3245, 122, 1573, 2164, 3468, 745, 4491, 4823],
 [15, 740, 3376, 1854, 2429, 4422, 1007, 3817, 2844, 3198, 4463, 1255, 670],
 [2466, 2150, 4254, 4758, 2644],
 [39, 2391, 1706, 3086, 554, 3693, 3256, 1848],
 [1246, 2218, 4551, 3245, 1047, 2108, 4551, 122],
 [2707, 2581, 3024, 382, 2108, 718, 3542, 2317],
 [1691, 108, 3331, 4977, 1457, 2225, 4716, 2668, 116],
 [3911, 4628, 1183, 329, 1085, 4372, 4252],
 [2108, 718, 389, 4180, 910, 1691, 1432, 1343, 277, 4898, 1640],
 [4697, 1630],
 [4135, 1302, 4467, 4946, 4593, 301, 2457, 1084],
 [1654, 2338, 1881, 718, 820, 4560],
 [3951,
  2430,
  4262,
  1909,
  492,
  4370,
  1986,
  4328,
  2063,
  2334,
  1578,
  1651,
  3810,
  3774,
  492,
  4370,
  3256,
  2986,
  2063,
  4030,
  3696,
  1578,

In [30]:
corpus[1]

'watch exact moment paul ryan commit polit suicid trump ralli video'

In [31]:
onehot_repr[1]

[3402, 1145, 674, 625, 186, 208, 4753, 2621, 3245, 4418, 4823]

### Embedding Representation

In [32]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3117 2108 2020 ...    0    0    0]
 [3402 1145  674 ...    0    0    0]
 [1335 1105 1197 ...    0    0    0]
 ...
 [2044 3245 3039 ...    0    0    0]
 [4838 2375 3935 ...    0    0    0]
 [3181  549 2819 ...    0    0    0]]

In [33]:
embedded_docs[1]

array([3402, 1145,  674,  625,  186,  208, 4753, 2621, 3245, 4418, 4823,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [34]:
embedded_docs[0]

array([3117, 2108, 2020,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [36]:
## Creating model
embedding_vector_features=40 ##features representation

model=Sequential()

model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))

model.add(Dense(1,activation='sigmoid'))


model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [37]:
len(embedded_docs),y.shape

(6335, (6335,))

In [38]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [39]:
X_final.shape,y_final.shape

((6335, 20), (6335,))

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [42]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=32)

Epoch 1/10
  1/133 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - accuracy: 1.0000 - loss: 0.0151

133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9651 - loss: 0.1088 - val_accuracy: 0.7480 - val_loss: 0.9098
Epoch 2/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9607 - loss: 0.1129 - val_accuracy: 0.7456 - val_loss: 1.0174
Epoch 3/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9689 - loss: 0.1043 - val_accuracy: 0.7370 - val_loss: 0.9362
Epoch 4/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9771 - loss: 0.0754 - val_accuracy: 0.7499 - val_loss: 1.0131
Epoch 5/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.9847 - loss: 0.0622 - val_accuracy: 0.7480 - val_loss: 1.1055
Epoch 6/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9870 - loss: 0.0524 - val_accuracy: 0.7370 - val_loss: 0.9603
Epoch 7/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9840 - loss: 0.0622 - val_accuracy: 0.7394 - val_loss: 1.0033
Epoch 8/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9868 - loss: 0.0542 - val_accuracy: 0.7422 - val_loss: 1.2764
Epoch 9/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.9880 - loss: 0.0482 - val_accuracy: 0.7441 - val_loss: 1.1003
Epoch 10/10
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.9880 - loss: 0.0457 - val_accuracy: 0.7317 - val_loss: 1.2794

In [44]:
y_pred=model.predict(X_test)

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

In [45]:
y_pred>=0.5

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [ True]])

In [46]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[765, 306],
       [248, 772]], dtype=int64)

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7350549976087997

### Adding Dropout

In [52]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

### Performance Metrics And Accuracy

In [53]:
y_pred=model.predict(X_test)

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

In [54]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
confusion_matrix(y_test,y_pred)

array([[1071,    0],
       [1020,    0]], dtype=int64)

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5121951219512195

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.51      1.00      0.68      1071
           1       0.00      0.00      0.00      1020

    accuracy                           0.51      2091
   macro avg       0.26      0.50      0.34      2091
weighted avg       0.26      0.51      0.35      2091

d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\PYTHON\PYTHON---3.11\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])